### ISSUE TITLE
Deserialize to ResourceMetrics struct

### ISSUE THREAD

**Issue by sabiurr** [open-telemetry/opentelemetry-go#1025]
Hi, I have a client that will send ResourceMetrics serialized from java and I want to be able to deserialize from golang. However, it seems this struct is internal. 

https://github.com/open-telemetry/opentelemetry-go/blob/master/internal/opentelemetry-proto-gen/metrics/v1/metrics.pb.go#L185

How can I get construct/deserialize this struct?

**Comment by MrAlias** [comment]
I don't know of any part of this code base that receives that proto. It is only used to send to the collector. In what way are you using this code?

**Comment by sabiurr** [comment]
We have a client that is using the opentelemetry java SDK and sending us payload of ResourceMetrics object. I want to be able to deserialize from golang listener side using the opentelemetry ResourceMetrics struct

**Comment by MrAlias** [comment]
> We have a client that is using the opentelemetry java SDK and sending us payload of ResourceMetrics object. I want to be able to deserialize from golang listener side using the opentelemetry ResourceMetrics struct

Hmm, I think I see. The proto project made the decision to decentralize the compilation of the proto in [this issue](https://github.com/open-telemetry/opentelemetry-proto/issues/79). To accommodate this decision this project generated Go code locally, but made the conscious decision to not expose this. The reasons for this included the goal of not polluting the package with the unrelated proto code base, not having to maintain version compatibility, or leaving the option open for optimized and unique encoding of the proto if desired in the future.

This means this repository should not be used as a dependency providing this code. This is the same position that [the collector](https://github.com/open-telemetry/opentelemetry-collector/tree/master/internal/data/opentelemetry-proto-gen) has taken as well.

I imagine you can follow the same pattern and setup an auto-generation pipeline in your codebase. Otherwise, it seems like opening an issue in https://github.com/open-telemetry/opentelemetry-proto to have this code moved back to a centralized location. It was also proposed to have this generated code in its own repository: https://github.com/open-telemetry/opentelemetry-proto/issues/79#issuecomment-593058471

**Comment by sabiurr** [comment]
I see. Just to confirm, if we want to deserialize this, we should generate the golang structs from proto files within our project?

**Comment by MrAlias** [comment]
> I see. Just to confirm, if we want to deserialize this, we should generate the golang structs from proto files within our project?

Correct.

Otherwise, you'll need to work with the https://github.com/open-telemetry/opentelemetry-proto to have them do so in a centralized location.

**Comment by MrAlias** [comment]
@sabiurr I'm going to close this as it seems to be resolved. Let me know if that is an error.
