### ISSUE TITLE
[Question] Prometheus Gauge in OpenTelemetry?

### ISSUE THREAD

**Issue by otherview** [open-telemetry/opentelemetry-go#1139]
Hi !

Similar to https://github.com/open-telemetry/opentelemetry-go/issues/708 I'm trying to model a Gauge using otel-go.
Finding it hard to wrap my head around it, can someone shine some light on this? 

The results seem to be accumulative either way I do it 🤔 

Using prometheus client:
```
func recordMetrics() {
	go func() {
		for {
			rtt.Set(rand.Float64() * 100)
			time.Sleep(2 * time.Second)
		}
	}()
}

var (
	rtt = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "RTT_things",
	})
)

func main() {
	recordMetrics()
	http.Handle("/metrics", promhttp.Handler())
	http.ListenAndServe(":2222", nil)
}
```

Using otel-go:
```
func initMeter() {

	exporter, err := prometheus.InstallNewPipeline(prometheus.Config{
		DefaultHistogramBoundaries: []float64{1, 100, 250, 500},
	})
	if err != nil {
		log.Panicf("failed to initialize prometheus exporter %v", err)
	}
	http.HandleFunc("/metrics", exporter.ServeHTTP)
	go func() {
		_ = http.ListenAndServe(":2222", nil)
	}()

	fmt.Println("Prometheus server running on :2222")
}

func main() {
	initMeter()

	meter := global.Meter("basicTest")
	ctx := context.Background()

	// RTT
	rttValue := metric.Must(meter).NewInt64UpDownCounter("rtt_meter")

	for {
		randVal := rand.Int63n(100)
		fmt.Println("rtt-> ", randVal)

		// either this
		// rttValue.Add(ctx, randVal)

		// or this
		meter.RecordBatch(ctx,
			[]label.KeyValue{},
			rttValue.Measurement(randVal),
		)

		time.Sleep(10 * time.Second)
	}
}
```

Rendering:
```
Prometheus server running on :2222
rtt->  10
rtt->  21
rtt->  37
----------
# HELP rtt_meter
# TYPE rtt_meter counter
rtt_meter 10
----------
# HELP rtt_meter
# TYPE rtt_meter counter
rtt_meter 31
----------
# HELP rtt_meter
# TYPE rtt_meter counter
rtt_meter 68
````

Thanks! 😃

**Comment by jmacd** [comment]
Ah, now that I see your example, the `ValueObserver` instrument (asynchronous) is well suited to your needs. Instead of defining a loop and a periodic gauge being Set, you'll define a `ValueObserver` callback that will be called once per collection interval and output a classic Gauge in both OTLP and Prometheus exporters.

You'll have fewer goroutines and arbitrary sleep statements then. See https://github.com/open-telemetry/opentelemetry-specification/issues/834

**Comment by otherview** [comment]
Thanks for the reply @jmacd ! ☺️ 

I'm still not able to achieve it though... 
This is returning an accumulative histogram, whereas I just want it to spit out the value that is "set". 

I feel like my approach to this is wrong 🤔 . Can you have a look ?

Given : 
```
func main() {
	initMeter()

	meter := global.Meter("basicTest")
	ctx := context.Background()

	observerLock := new(sync.RWMutex)
	observerValueToReport := int64(0)

	// Latency
	cb := func(_ context.Context, result metric.Int64ObserverResult) {
		(*observerLock).RLock()
		value := observerValueToReport
		(*observerLock).RUnlock()
		result.Observe(value)
	}

	_ = metric.Must(meter).NewInt64ValueObserver("latency_meter", cb)

	for {
		randVal := rand.Int63n(100)
		fmt.Println("rtt-> ", randVal)

		(*observerLock).RLock()
		observerValueToReport = randVal
		(*observerLock).RUnlock()

		time.Sleep(10 * time.Second)
	}
}
```
This renders:
```
Prometheus server running on :2222
rtt->  10
rtt->  51
rtt->  21

--------
# HELP latency_meter
# TYPE latency_meter histogram
latency_meter_bucket{le="1"} 0
latency_meter_bucket{le="100"} 1
latency_meter_bucket{le="250"} 1
latency_meter_bucket{le="500"} 1
latency_meter_bucket{le="+Inf"} 1
latency_meter_sum 10
latency_meter_count 1

--------
# HELP latency_meter
# TYPE latency_meter histogram
latency_meter_bucket{le="1"} 0
latency_meter_bucket{le="100"} 3
latency_meter_bucket{le="250"} 3
latency_meter_bucket{le="500"} 3
latency_meter_bucket{le="+Inf"} 3
latency_meter_sum 71       -> 10          + 10     + 51
latency_meter_count 3      -> obs1       obs1   obs2

```

**Comment by nilebox** [comment]
This is probably because Prometheus is using simple selector: https://github.com/open-telemetry/opentelemetry-go/blob/f995380e5848d2b9287f8b8e0608a4bda6f986d5/exporters/metric/prometheus/prometheus.go#L149

which uses histogram distribution for ValueObserver: https://github.com/open-telemetry/opentelemetry-go/blob/c9726efd6075c1dccbafc5a17724f0299fd1998a/sdk/metric/selector/simple/simple.go#L127-L128

The workaround for now is to implement a custom selector which uses "LastValue" aggregation for ValueObserver, this is [what we did in Cloud Monitoring](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/ef5e24b7fcfcb5ff45f1a1762fc0a090c5b0ab3a/exporter/metric/selector.go#L46-L47).

**Comment by MrAlias** [comment]
Talking about this in the SIG meeting today the proposal put forth was to include a selector similar to what @nilebox showed was done in the Google Cloud Monitoring exporter in the main project. Additionally add the functionality to the prometheus and cortext exporters to be configured with a user defined selector. That way, even though the default will still be the Histogram selector, it will allow users to solve this problem in a more standard way.

It was also brought up that this is likely something the Views API is well suited to address. The long-term solution would be to address this configuration there.
