### ISSUE TITLE
http plug-in problem

### ISSUE THREAD

**Issue by congim** [open-telemetry/opentelemetry-go#120]
I tried to run the http instance code，and use wireshark to capture network messages,why didn't i find traceID spanID in the http message?

**Comment by congim** [comment]
network msg:
```
GET /hello HTTP/1.1
Host: localhost:7777
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip

HTTP/1.1 200 OK
Date: Thu, 12 Sep 2019 02:17:58 GMT
Content-Length: 14
Content-Type: text/plain; charset=utf-8

Hello, world!
```

**Comment by congim** [comment]
I traced the code and found a NoopTracer～ ~

**Comment by congim** [comment]
Do I need to implement tracer myself if I want to use this sdk?

**Comment by congim** [comment]
Do I need to implement this tracer myself?

**Comment by iredelmeier** [comment]
@congim rather than implementing the tracer yourself, you can use the SDK via [`Register`](https://godoc.org/go.opentelemetry.io/sdk/trace#Register with an exporter registered via [`RegisterExporter`](https://godoc.org/go.opentelemetry.io/sdk/trace#RegisterExporter). Currently, the only out-of-the-box exporter is the Jaeger exporter.

Here's a [complete example](https://github.com/open-telemetry/opentelemetry-go/blob/8af7978f42700347ab4f7a2feb8e941e70a31216/exporter/trace/jaeger/example/main.go).  Hope that helps!

**Comment by congim** [comment]
@iredelmeier nice, thank you!
