### ISSUE TITLE
API: rename tag to correlation context

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/opentelemetry-go#122]
Rename tags to correlation contextas per the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-distributedcontext.md).

**Comment by akvanhar** [comment]
I can pick this up.

**Comment by rghetia** [comment]
> Sounds like someone else might be picking this up. If not, please let me know and I'll pick it up.

Earlier this morning I asked @sayboras to pick this up.

**Comment by sayboras** [comment]
I am working on this

**Comment by rghetia** [comment]
> I am working on this

@sayboras, any updates on this?

**Comment by sayboras** [comment]
@rghetia this seems complicated than I thought, maybe because I didn't understand the spec well. I am a little confused about terminologies. Some of them are quite different with opentracing that I used to work on (open tracing + datadog). 

Feel free to assign this issue to someone else. I will find other item to start with.

**Comment by rghetia** [comment]
@akvanhar would you like to take this?

**Comment by akvanhar** [comment]
PR for this here: https://github.com/open-telemetry/opentelemetry-go/pull/178

**Comment by rghetia** [comment]
fixed by #178
