### ISSUE TITLE
Span.End contract unclear

### ISSUE THREAD

**Issue by zombiezen** [open-telemetry/opentelemetry-go#1275]
From [`go.opentelemetry.io/otel/api/trace.Span` docs](https://pkg.go.dev/go.opentelemetry.io/otel@v0.13.0/api/trace#Span.End):

```go
// End completes the span. No updates are allowed to span after it
// ends. The only exception is setting status of the span.
End(options ...SpanOption)
```

I read this as it being safe to write code like this:

```go
span.End()
span.SetStatus(codes.Error, "bork")
```

But I'm left with confusion as to when a span would be sent to an exporter and in what state. Does a span get sent after some period of time after the `End`? Can this race with `SetStatus`? etc. I haven't dug enough into the details to know how this is implemented.

I think removing the exception of "setting status of the span" from `Span.End` makes for a more comprehensible (and hopefully easier to implement!) API.

/cc @rakyll

**Comment by rakyll** [comment]
FYI, according to the spec, status must not be changed after span's end time has been set. This behavior seems inconsistent with the spec. See https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md

**Comment by MrAlias** [comment]
Yeah, we should try to compliant with the specification, but my understanding from the specification is it is _recommended_ that calls to change the state of a span post `End` being called be ignored: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#end

> Implementations SHOULD ignore all subsequent calls to End and any other Span methods, i.e. the Span becomes non-recording by being ended (there might be exceptions when Tracer is streaming events and has no mutable state associated with the Span).

@rakyll is there another location where it is stated as a requirement?

If I recall correctly, the decision to allow Status changes after the span has ended was made to allow for two explicit cases:

1. The span tracking a function that returned a recoverable error would need to be changed from `Error` to `Ok`. This would have to be done after the function had returned and ended its span.
2. When a batch or stream of operations are performed and all represented with spans, if the overall batch or stream failed the spans would need to be marked as `Error` after they had ended

While these both seem like valid reasons to allow this behavior, @zombiezen you make a good point that it presents an undefined behavior situation at best and possibly a race-condition at worst. The existing `SpanProcessors` have no concept, nor should they, that a span needs to not be sent because it could undergo future changes.

I'm in-favor of changing the behavior, but am also interested to hear what the other @open-telemetry/go-approvers think.

**Comment by rakyll** [comment]
@MrAlias, the spec mentions an exception at https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#span-operations

"With the exception of the function to retrieve the Span's SpanContext and recording status, none of the below may be called after the Span is finished."

I think we can clarify the first section in the spec. I assumed recording status was prohibited.

**Comment by Aneurysm9** [comment]
> @MrAlias, the spec mentions an exception at https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#span-operations
> 
> "With the exception of the function to retrieve the Span's SpanContext and recording status, none of the below may be called after the Span is finished."
> 
> I think we can clarify the first section in the spec. I assumed recording status was prohibited.

I suspect that this is a case of imprecise writing in the spec sending us down [a garden path](https://en.wikipedia.org/wiki/Garden-path_sentence).  It seems that @MrAlias and @rakyll are interpreting "recording" as a verb operating on the span's status, but I suspect that it is instead part of the noun phrase "recording status" referring to whether the span was recording data or not.  

This is supported by the fact that `Get Context` and `IsRecording` are the first two operations listed.  Also, `IsRecording` includes this discussion of its behavior after a span has ended:

> After a Span is ended, it usually becomes non-recording and thus IsRecording SHOULD consequently return false for ended Spans. Note: Streaming implementations, where it is not known if a span is ended, are one expected case where IsRecording cannot change after ending a Span.

**Comment by MrAlias** [comment]
> This would leave the allowed operations after span end as "retriev[ing both] the Span's SpanContext and [its] recording status".

This makes sense to me :+1:

**Comment by MrAlias** [comment]
To resolve this we should fix the comment and open Bugs to address and SDK behavior that does not conform to this.
