### ISSUE TITLE
API: Add TraceState to SpanContext

### ISSUE THREAD

**Issue by gavinservai** [open-telemetry/opentelemetry-go#1302]
The spec mentions TraceState under SpanContext:
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#spancontext

The previous issue that was filed for this was closed, mentioning that tracestate is not a part of the spec anymore.
I'm not sure why this was done, as an open PR from the spec was linked - and that PR did not end up getting merged into the actual spec

https://github.com/open-telemetry/opentelemetry-go/issues/74

**Comment by matej-g** [comment]
Yes, looks like that issue was prematurely closed together with [the original PR](https://github.com/open-telemetry/opentelemetry-go/pull/81#issuecomment-519611895), while recently `TraceState` has been [moved to API](https://github.com/open-telemetry/opentelemetry-specification/pull/922) and operations on it have been specified.

@MrAlias if you agree I would like to take this one.
