### ISSUE TITLE
grouping attributes

### ISSUE THREAD

**Issue by schmurfy** [open-telemetry/opentelemetry-go#1383]
This is not an issue but I don't know where to ask and could not find any answers on this: is there a way to group attributes with opentelemetry ?

Here is what I means: 
```go
span.SetAttributes(
	label.Int("request.max_count", count),
	label.Int("request.from", "..."),
	label.Int("request.to", "..."),
)


span.SetAttributes(
	label.Int("response.count", len(ret)),
)
```

In that cas it would be nice to be able to group `request` attributes and `response` attributes.
Is there a cleaner way to achieve this ?

**Comment by MrAlias** [comment]
Thanks for the question, and the interesting proposal.

If I understand the proposal correctly, you should be able to group attributes in whatever form you like at the export level. If you want to write an exporter to accomplish this grouping it should be possible.

However, from the perspective of OpenTelemetry, attributes are all treated a singular the batch of annotation for a signal. This is the defined behavior [at the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/common/common.md#attributes). Because of this, implementing a grouping strategy is not something we plan to support in the API or SDK.
