### ISSUE TITLE
Spec Conformance Review: Traces/Tracer

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1589]
Please review the `Traces/Tracer` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) and the corresponding implementations in the [core](https://github.com/open-telemetry/opentelemetry-go) and [contrib](https://github.com/open-telemetry/opentelemetry-go-contrib) repositories.  For each entry in the compliance matrix please ensure that either the implementation conforms to [the specification](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.0.1) or that an issue is created in the relevant repository to address the non-conformance.  Ignore any entries presently in the matrix for Go, assume that all features must be freshly evaluated.

**Comment by XSAM** [comment]
[The Span Creation From The Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#span-creation)

> Span creation MUST NOT set the newly created Span as the currently active Span by default, but this functionality MAY be offered additionally as a separate operation.

I'm not sure about the meaning of `currently active Span`.

**Comment by MrAlias** [comment]
> I'm not sure about the meaning of `set the newly created Span as the currently active Span`.

My understanding from talking with the Java SIG folks is they have a scope concept that holds an implied span that encapsulates operations. Meaning that functions will be called and return without having to directly pass or manage a span and one will be used to encapsulate the work they are doing. We don't have that scoped concept of an implied span. The active span is the one passed to a function until you create a child span from that. Based on this the active span concept is not applicable here or you could interpret it as the explicit span (when you create a new span it _is_ set to active because it is the span actively being recorded in the function).

I see you opened a specification issue. Hopefully, this is in line with what is being said there.

**Comment by XSAM** [comment]
# [The specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#tracer)

> The Tracer MUST provide functions to:
>
>   Create a new Span (see the section on Span)

https://pkg.go.dev/go.opentelemetry.io/otel/trace#Tracer

## [Span Creation](https://pkg.go.dev/go.opentelemetry.io/otel/trace#Tracer)

> Span creation MUST NOT set the newly created Span as the currently active Span by default, but this functionality MAY be offered additionally as a separate operation.

Go uses explicit `Context`, which is not suitable for this case. [Tracking Issue](https://github.com/open-telemetry/opentelemetry-specification/issues/1508) to make this paragraph more clear.


| Features of Tracer | Go |
| -- | -- | 
| Create a new Span | + |
| Get active Span (the tracer should call `Context` API to get active Span, [Tracking Issue](https://github.com/open-telemetry/opentelemetry-specification/issues/1493))  | + |
| Mark Span active | + |
| Safe for concurrent calls | +, [the proof of test](https://github.com/open-telemetry/opentelemetry-go/pull/1665) |
