### ISSUE TITLE
Spec Conformance Review: Traces/Span attributes

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1592]
- [x] Review [Span Operation -- Set Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#set-attributes) and [Common specification concepts -- Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/common/common.md#attributes) sections and identify all normative requirements they contains.
- [x] Validate our implementation of the specification to conform or not. If it conforms, document the conformity here. If it does not open an Issue or PR track the work.
- [x] Review the `Traces/Span attributes` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md).
- [x] If there are any items listed in matrix that are not required by the specification, need clarification, or are in conflict with the specification open a PR in the specification to correct it.
- [x] Update the matrix with the current state of Go (existing entries for Go should be ignored). If Go does not provide support for an item listed be sure to link to the Issue/PR tracking the work to support it.

**Comment by MrAlias** [comment]
> A Span MUST have the ability to set Attributes associated with it.

[SetAttributes method](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/trace/trace.go#L438-L441)

> The Span interface MUST provide:
> An API to set a single Attribute where the attribute properties are passed as arguments.

[SetAttributes method is variadic and a single key/value can be passed as an argument](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/trace/trace.go#L438-L441)

> This MAY be called SetAttribute.

[we call it SetAttributes](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/trace/trace.go#L438-L441)

> To avoid extra allocations some implementations may offer a separate API for each of the possible value types.
[We do not](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/trace/trace.go#L438-L441)

> Setting an attribute with the same key as an existing attribute SHOULD overwrite the existing attribute's value.

[That is how we document our implementation](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/sdk/trace/span.go#L186-L187), [and that is how it is implemented](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/sdk/trace/attributesmap.go#L45-L62)

> Note that the OpenTelemetry project documents certain "standard attributes" that have prescribed semantic meanings.

:+1:

> Note that Samplers can only consider information already present during span creation.
> Any changes done later, including new or changed attributes, cannot change their decisions.

This seems intended for an instrumentation author, but to verify [this does not initiate another sample decision](https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/sdk/trace/span.go#L190-L195)

**Comment by MrAlias** [comment]
> An Attribute MUST have the following properties:
> The attribute key, which MUST be a non-null and non-empty string.

- [The key type is a string (cannot be nil)](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/key.go#L17-L19)
- Tracking non-empty requirement [here](https://github.com/open-telemetry/opentelemetry-go/issues/1657)

> The attribute value, which is either:
> - A primitive type: string, boolean, double precision floating point (IEEE 754-1985) or signed 64 bit integer.

  - [attribute.String](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/key.go#L60-L71)
  - [attribute.Bool](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/key.go#L21-L32)
  - [attribute.Float64](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/key.go#L47-L58)
  - [attribute.Int64](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/key.go#L34-L45)

> - An array of primitive type values.

[attribute.Array](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/key.go#L91-L102)

>   The array MUST be homogeneous, i.e. it MUST NOT contain values of different types.

[homogeneous values](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/value.go#L95-L122)

>   For protocols that do not natively support array values such values SHOULD be represented as JSON strings.

N/A

> Attribute values expressing a numerical value of zero, an empty string, or an empty array are considered meaningful and MUST be stored and passed on to processors / exporters.

:heavy_check_mark:

> Attribute values of null are not valid and attempting to set a null value is undefined behavior.

[We store it as a string value of "<nil>"](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/kv.go#L75-L77)

> null values SHOULD NOT be allowed in arrays.

[They are not allowed](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/value.go#L117-L118)

> However, if it is impossible to make sure that no null values are accepted (e.g. in languages that do not have appropriate compile-time type checking), null values within arrays MUST be preserved as-is (i.e., passed on to span processors / exporters as null).

N/A

> If exporters do not support exporting null values, they MAY replace those values by 0, false, or empty strings.
> This is required for map/dictionary structures represented as two arrays with indices that are kept in sync (e.g., two attributes header_keys and header_values, both containing an array of strings to represent a mapping header_keys[i] -> header_values[i]).

Not related to attributes or SDK implementations.

**Comment by MrAlias** [comment]
## [Spec Compliance Matrix -- Traces/Span attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/spec-compliance-matrix.md)

- :heavy_check_mark: SetAttribute
  - [SetAttributes method](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/trace/trace.go#L438-L441)
- :heavy_check_mark: Set order preserved
  - [The eviction list is used as a FILO stack to preserve order](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/sdk/trace/attributesmap.go#L74-L76)
- :heavy_check_mark: String type
  - [attribute.String](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/key.go#L60-L71)
- :heavy_check_mark: Boolean type
  - [attribute.Bool](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/key.go#L21-L32)
- :heavy_check_mark: Double floating-point type
  - [attribute.Float64](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/key.go#L47-L58)
- :heavy_check_mark: Signed int64 type
  - [attribute.Int64](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/key.go#L34-L45)
- :heavy_check_mark: Array of primitives (homogeneous)
  - [attribute.Array](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/key.go#L91-L102)
  - [homogeneous values](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/value.go#L95-L122)
- :heavy_check_mark: `null` values documented as invalid/undefined
  - This isn't a normative requirement of the specification to have this documented but ...
  - [We check the attribute is not `INVALID`](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/sdk/trace/span.go#L494-L496)
  - [We document that for a "value [...] not an array or slice of these [primitive] types an INVALID value is returned](https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/attribute/value.go#L98-L99)
- :heavy_check_mark: Unicode support for keys and string values
  - [Go strings are composed of rune literals: "since Go source text is Unicode characters encoded in UTF-8, multiple UTF-8-encoded bytes may represent a single integer value](https://golang.org/ref/spec#Rune_literals)
