### ISSUE TITLE
Spec Conformance Review: Context Propagation/Propagators

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1601]
- [x] Review the [Propagators](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/context/api-propagators.md) API specification and identify all normative requirements it contains.
- [x] Validate our implementation of the specification to conform or not. If it conforms, document the conformity here. If it does not open an Issue or PR track the work.
- [x] Review the `Context Propagation` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md).
- [x] If there are any items listed in matrix that are not required by the specification, need clarification, or are in conflict with the specification open a PR in the specification to correct it.
- [x] Update the matrix with the current state of Go (existing entries for Go should be ignored). If Go does not provide support for an item listed be sure to link to the Issue/PR tracking the work to support it.

**Comment by MrAlias** [comment]
## [Propagators](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/context/api-propagators.md)

> The Propagators API currently defines one `Propagator` type:
>
> - `TextMapPropagator` is a type that inject values into and extracts values from carriers as string key/value pairs.

[TextMapPropagator](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#TextMapPropagator)

> ### Operations
>
> `Propagator`s MUST define `Inject` and `Extract` operations, in order to write values to and read values from carriers respectively.
> Each `Propagator` type MUST define the specific carrier type and MAY define additional parameters.


[TextMapPropagator is defined this way](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#TextMapPropagator)

> #### Inject
>
> Injects the value into a carrier.
> For example, into the headers of an HTTP request.
>
> Required arguments:
>
> - A `Context`.
>   The Propagator MUST retrieve the appropriate value from the `Context` first, such as `SpanContext`, `Baggage` or another cross-cutting concern context.
> - The carrier that holds the propagation fields.
>   For example, an outgoing message or HTTP request.

[TextMapPropagator.Inject is defined this way](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#TextMapPropagator)

> #### Extract
>
> Extracts the value from an incoming request.
> For example, from the headers of an HTTP request.
>
> If a value can not be parsed from the carrier, for a cross-cutting concern, the implementation MUST NOT throw an exception and MUST NOT store a new value in the `Context`, in order to preserve any previously existing valid value.
>
> Required arguments:
>
> - A `Context`.
> - The carrier that holds the propagation fields.
>   For example, an incoming message or http response.
>
> Returns a new `Context` derived from the `Context` passed as argument, containing the extracted value, which can be a `SpanContext`, `Baggage` or another cross-cutting concern context.

[TextMapPropagator.Extract is defined this way](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#TextMapPropagator)

> In order to increase compatibility, the key/value pairs MUST only consist of US-ASCII characters that make up valid HTTP header fields as per [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2).

[TextMapCarrier uses Go strings which support UTF-8 (a superset of US-ASCII)](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#TextMapCarrier)

> `Getter` and `Setter` are optional helper components used for extraction and injection respectively, and are defined as separate objects from the carrier to avoid runtime allocations, by removing the need for additional interface-implementing-objects wrapping the carrier in order to access its contents.
>
> `Getter` and `Setter` MUST be stateless and allowed to be saved as constants, in order to effectively avoid runtime allocations.

We do not implement these optional components. The `Get` and `Set` method of the `TextMapCarrier` server this functionality without needing to be additional components.

> ### Fields
>
> The predefined propagation fields.
> If your carrier is reused, you should delete the fields here before calling [inject](#inject).
>
> Fields are defined as string keys identifying format-specific components in a carrier.
>
> For example, if the carrier is a single-use or immutable request object, you don't need to clear fields as they couldn't have been set before.
> If it is a mutable, retryable object, successive calls should clear these fields first.
>
> The use cases of this are:
>
> - allow pre-allocation of fields, especially in systems like gRPC Metadata
> - allow a single-pass over an iterator
>
> Returns list of fields that will be used by the `TextMapPropagator`.
>
> Observe that some `Propagator`s may define, besides the returned values, additional fields with variable names.
> To get a full list of fields for a specific carrier object, use the [Keys](#keys) operation.

[TextMapPropagator.Fields is defined this way](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#TextMapPropagator)

> ### TextMap Inject
>
> Injects the value into a carrier.
> The required arguments are the same as defined by the base [Inject](#inject) operation.
>
> Optional arguments:
>
> - A `Setter` to set a propagation key/value pair.
>   Propagators MAY invoke it multiple times in order to set multiple pairs.
>   This is an additional argument that languages are free to define to help inject data into the carrier.

We do not implement this optional argument because we do not implement the optional setter.

> ### TextMap Extract
>
> Extracts the value from an incoming request.
> The required arguments are the same as defined by the base [Extract](#extract) operation.
>
> Optional arguments:
>
> - A `Getter` invoked for each propagation key to get.
> This is an additional argument that languages are free to define to help extract data from the carrier.

We do not implement this optional argument because we do not implement the optional getter.

> Returns a new `Context` derived from the `Context` passed as argument.

[TextMapPropagator.Extract is defined this way](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#TextMapPropagator)

> ## Injectors and Extractors as Separate Interfaces
>
> Languages can choose to implement a `Propagator` type as a single object exposing `Inject` and `Extract` methods, or they can opt to divide the responsibilities further into individual `Injector`s and `Extractor`s.
> A `Propagator` can be implemented by composing individual `Injector`s and `Extractors`.

We implement a unified propagator.

> ## Composite Propagator
>
> Implementations MUST offer a facility to group multiple `Propagator`s from different cross-cutting concerns in order to leverage them as a single entity.

[NewCompositeTextMapPropagator](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#NewCompositeTextMapPropagator)

> There MUST be functions to accomplish the following operations.
>
> - Create a composite propagator
> - Extract from a composite propagator
> - Inject into a composite propagator

[NewCompositeTextMapPropagator](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#NewCompositeTextMapPropagator) supports the creation of a composite propagator and returns a `TextMapPropagator` that supports both extract and inject.

> ### Create a Composite Propagator
>
> Required arguments:
>
> - A list of `Propagator`s or a list of `Injector`s and `Extractor`s.
>
> Returns a new composite `Propagator` with the specified `Propagator`s.

[This is how NewCompositeTextMapPropagator is defined and operates](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#NewCompositeTextMapPropagator)

> ### Composite Extract
>
> Required arguments:
>
> - A `Context`.
> - The carrier that holds propagation fields.
> - The instance of `Getter` invoked for each propagation key to get.

An instance of `Getter` is not accepted, though it should not be required. [Change to specification](https://github.com/open-telemetry/opentelemetry-specification/pull/1541/files)

>
> ### Composite Inject
>
> Required arguments:
>
> - A `Context`.
> - The carrier that holds propagation fields.
> - The `Setter` to set a propagation key/value pair.
>   Propagators MAY invoke it multiple times in order to set multiple pairs.

An instance of `Setter` is not accepted, though it should not be required. [Change to specification](https://github.com/open-telemetry/opentelemetry-specification/pull/1541/files)

> The OpenTelemetry API MUST provide a way to obtain a propagator for each supported `Propagator` type.

[GetTextMapPropagator](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/#GetTextMapPropagator)

> The OpenTelemetry API MUST use no-op propagators unless explicitly configured otherwise.

[This is how it is implemented](https://github.com/open-telemetry/opentelemetry-go/blob/bb4c297eb36f6af082bfa1d3216d33bd90da05f0/internal/global/propagator.go#L38-L42)

> Platforms such as ASP.NET may pre-configure out-of-the-box propagators.
> If pre-configured, `Propagator`s SHOULD default to a composite `Propagator` containing the W3C Trace Context Propagator and the Baggage `Propagator` specified in the [Baggage API](../baggage/api.md#propagation).
> These platforms MUST also allow pre-configured propagators to be disabled or overridden.

No pre-configured `Propagator`s are provided.

> ### Get Global Propagator
>
> This method MUST exist for each supported `Propagator` type.
>
> Returns a global `Propagator`.
> This usually will be composite instance.

There is only one defined Propagator type, [GetTextMapPropagator](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/#GetTextMapPropagator) is the global get function implementing this requirement for that type.

> ### Set Global Propagator
>
> This method MUST exist for each supported `Propagator` type.
>
> Sets the global `Propagator` instance.
>
> Required parameters:
>
> - A `Propagator`.
>   This usually will be a composite instance.

There is only one defined Propagator type, [SetTextMapPropagator](https://pkg.go.dev/go.opentelemetry.io/otel/@v0.18.0/#SetTextMapPropagator) is the global set function implementing this requirement for that type.

> ## Propagators Distribution
>
> The official list of propagators that MUST be maintained by the OpenTelemetry organization and MUST be distributed as OpenTelemetry extension packages:
>
> * [W3C TraceContext](https://www.w3.org/TR/trace-context/).
>   MAY alternatively be distributed as part of the OpenTelemetry API.

https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#TraceContext

> * [W3C Baggage](https://w3c.github.io/baggage).
>   MAY alternatively be distributed as part of the OpenTelemetry API.

https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#Baggage

> * [B3](https://github.com/openzipkin/b3-propagation).

https://pkg.go.dev/go.opentelemetry.io/contrib/propagators@v0.18.0/b3

> * [Jaeger](https://www.jaegertracing.io/docs/latest/client-libraries/#propagation-format).

https://pkg.go.dev/go.opentelemetry.io/contrib/propagators@v0.18.0/jaeger

> This is a list of additional propagators that MAY be maintained and distributed as OpenTelemetry extension packages:
>
> * [OT Trace](https://github.com/opentracing?q=basic&type=&language=).
>   Propagation format used by the OpenTracing Basic Tracers.
>   It MUST NOT use `OpenTracing` in the resulting propagator name as it is not widely adopted format in the OpenTracing ecosystem.

https://pkg.go.dev/go.opentelemetry.io/contrib/propagators@v0.18.0/ot

> Additional `Propagator`s implementing vendor-specific protocols such as AWS X-Ray trace header protocol MUST NOT be maintained or distributed as part of the Core OpenTelemetry repositories.

Based [this comment](https://github.com/open-telemetry/opentelemetry-specification/issues/1047#issuecomment-703759057) having the [AWS XRay Propagator](https://pkg.go.dev/go.opentelemetry.io/contrib/propagators/aws@v0.18.0/xray) in contrib seems compliant.

> ### B3 Requirements
>
> B3 has both single and multi-header encodings.
> It also has semantics that do not map directly to OpenTelemetry such as a debug trace flag, and allowing spans from both sides of request to share the same id.
> To maximize compatibility between OpenTelemetry and Zipkin implementations, the following guidelines have been established for B3 context propagation.
>
> #### B3 Extract
>
> When extracting B3, propagators:
>
> * MUST attempt to extract B3 encoded using single and multi-header formats.

[That is how it is implemented](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/839e505a67ca9fb5a3089cd1af5943061fcaf1ef/propagators/b3/b3_propagator.go#L146-L173)

>   The single-header variant takes precedence over the multi-header version.

[It is](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/839e505a67ca9fb5a3089cd1af5943061fcaf1ef/propagators/b3/b3_propagator.go#L152)

> * MUST preserve a debug trace flag, if received, and propagate it with subsequent requests.
>   Additionally, an OpenTelemetry implementation MUST set the sampled trace flag when the debug flag is set.

It is:

- https://github.com/open-telemetry/opentelemetry-go-contrib/blob/839e505a67ca9fb5a3089cd1af5943061fcaf1ef/propagators/b3/b3_propagator.go#L217
- https://github.com/open-telemetry/opentelemetry-go-contrib/blob/839e505a67ca9fb5a3089cd1af5943061fcaf1ef/propagators/b3/b3_propagator.go#L338

Though the form this is done may need to change: https://github.com/open-telemetry/opentelemetry-go/issues/1515

> * MUST NOT reuse `X-B3-SpanId` as the id for the server-side span.

This field is used in the parent span context. The parent span context span ID [is not used to set the span ID of any created spans if using the default span ID generator](https://github.com/open-telemetry/opentelemetry-go/blob/8b1be11a549eefb6efeda2f940cbda70b3c3d08d/sdk/trace/id_generator.go#L40-L47).

> #### B3 Inject
>
> When injecting B3, propagators:
>
> * MUST default to injecting B3 using the single-header format

out of compliance, tracking [here](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/613)

> * MUST provide configuration to change the default injection format to B3 multi-header

Set with the [`InjectEncoding` field](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/839e505a67ca9fb5a3089cd1af5943061fcaf1ef/propagators/b3/b3_propagator.go#L93-L96)

> * MUST NOT propagate `X-B3-ParentSpanId` as OpenTelemetry does not support reusing the same id for both sides of a request.

[It is not](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/839e505a67ca9fb5a3089cd1af5943061fcaf1ef/propagators/b3/b3_propagator.go#L126-L142)

**Comment by MrAlias** [comment]
## [spec-compliance-matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#context-propagation)

| Feature                                                                          | Go |
|----------------------------------------------------------------------------------|----|
| Composite Propagator                                                             | [+](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#NewCompositeTextMapPropagator) |
| Global Propagator                                                                | + [1](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/#GetTextMapPropagator), [2](https://pkg.go.dev/go.opentelemetry.io/otel/@v0.18.0/#SetTextMapPropagator) |
| TraceContext Propagator                                                          | [+](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#TraceContext)   |
| B3 Propagator                                                                    | [+](https://pkg.go.dev/go.opentelemetry.io/contrib/propagators@v0.18.0/b3)   |
| Jaeger Propagator                                                                | [+](https://pkg.go.dev/go.opentelemetry.io/contrib/propagators@v0.18.0/jaeger)   |
| [TextMapPropagator](specification/context/api-propagators.md#textmap-propagator) | [+](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#TextMapPropagator)   |
| Fields                                                                           | + [TextMapPropagator.Fields](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#TextMapPropagator)   |
| Setter argument                                                                  | N/A OPTIONAL not impmetented  |
| Getter argument                                                                  | N/A OPTIONAL not impmetented  |
| Getter argument returning Keys                                                   | N/A OPTIONAL not impmetented  |

**Comment by Cirilla-zmh** [comment]
Hello everyone,

I'm currently facing some challenges with understanding the Fields method of the TextMapPropagator. Could you advise me on the appropriate time to invoke this method?

I'm in the process of developing a multi-protocol propagator capable of dispatching calls to different propagators, each responsible for handling various tracing protocols as determined by the headers in the Request. For instance, if an incoming remote call includes the header "traceparent", the propagator should execute an Extract operation using the W3C protocol. Conversely, if the header "X-B3-TraceId" is present, the extraction would follow the Zipkin protocol.

In such scenarios, the Fields method would return a variable protocol. However, since the context is not a parameter of this method, I'm unable to determine the protocol for the given trace context. What is the best practice here – should I return all possible headers?

I'd appreciate your guidance on this matter!
