### ISSUE TITLE
Add cusomterSpanID config for create spanContext

### ISSUE THREAD

**Issue by llhhbc** [open-telemetry/opentelemetry-go#1630]
I have a project that collect all event logs to jaeger. So I need set customer spanID when I create spanContext.
The `TracerProviderOption` has `WithIDGenerator`, but It doesn't work. Because the progress is has done, I just collect the ids of every program and report to jaeger. every spanID must set by myself.

I have create a pull request of: https://github.com/open-telemetry/opentelemetry-go/pull/1623

**Comment by Aneurysm9** [comment]
Are you attempting to create a system to translate log entries that already have trace context information into spans that can be sent to Jaeger using the OTel Go Jaeger exporter?  I guess I'm having trouble understanding the problem you're trying to solve so it is hard for me to assess whether your proposed solution is good and/or viable.  It seems suspect, however, since external span context information should be obtained through the propagation system and newly created spans should have their IDs generated by an `IDGenerator`.  

I think the [collector](https://github.com/open-telemetry/opentelemetry-collector) might provide a better framework for constructing a system that can convert log entries into Jaeger spans.  Indeed, the language you're using seems overly domain-specific for something that would be included in a general purpose SDK like OTel Go.  I don't believe that we reference `customer` as a concept anywhere in the codebase.

**Comment by llhhbc** [comment]
Thanks, I will try to use collector  solve.

**Comment by llhhbc** [comment]
I am trying to write a tool to analyze the audit log of k8s, classify the resources of the operation, and output it to yaeger for complete resource operation path tracking. Therefore, the traceID and spanID used in the span have been clarified in advance, and what I need to do is to report in accordance with yaeger's rules. I wonder if you have a better suggestion?

**Comment by llhhbc** [comment]
I have create IdGenerator to solve

```
type MyIdGenerator struct {
	TraceId trace.TraceID
	SpanID trace.SpanID

	sync.Mutex
	randSource *rand.Rand
}
```

I will set traceID and spanID before call StartSpan.

**Comment by MrAlias** [comment]
Closing at this sounds resolved.
