### ISSUE TITLE
HTTP Span Attributes: `http.url` must not contain username / password

### ISSUE THREAD

**Issue by matej-g** [open-telemetry/opentelemetry-go#1675]
As is stated in the recent [specification change ](https://github.com/open-telemetry/opentelemetry-specification/pull/1502):

> `http.url` MUST NOT contain credentials passed via URL in form of `https://username:password@www.example.com/`. In such case the attribute's value should be `https://www.example.com/`.

This should be reflected in [`HTTPClientAttributesFromHTTPRequest`](https://github.com/open-telemetry/opentelemetry-go/blob/e9b9aca8a6dc8cd0b13ffea4f7a26186f4b316fd/semconv/http.go#L134)

**Comment by veera83372** [comment]
I understand this is coming from spec but for enduser it won't be evident that URL was containing username and password when it got here. Instead if we have redacted version like `https://***:***www.example.com/` it will be more evident in expressing URL contains username and password but they are redacted for security reasons. 

If we don't go with redacted version it might cause ambiguity for someone checking if url contains creds or not because in span with creds and without creds will be same.

**Comment by matej-g** [comment]
> If we don't go with redacted version it might cause ambiguity for someone checking if url contains creds or not because in span with creds and without creds will be same.

Yes, I think this could be a valid concern. However, it seems the specification suggests to drop everything (see the quoted excerpt in the issue description, also see the [discussion](https://github.com/open-telemetry/opentelemetry-specification/pull/1502#discussion_r587860542)). Maybe in such cases this could be alleviated in other way, perhaps adding an attribute, if desired?
