### ISSUE TITLE
Support multiple resources/controllers

### ISSUE THREAD

**Issue by skonto** [open-telemetry/opentelemetry-go#1716]
* What is the proper way to add multiple resource support? I am looking at the comment [here](https://github.com/open-telemetry/opentelemetry-go/blob/4beb70416e1272c578edfe1d5f88a3a2236da178/exporters/metric/prometheus/prometheus.go#L55) and that lock is used only to get the exporter's controller during collector's collect calls. Should each prometheus exporter support an array of controllers instead? 
* What happens when a resource is dynamically managed due its short lifecycle and we want to remove it from a specific controller, is there a way to do so?

**Comment by skonto** [comment]
@MrAlias is this part of the roadmap? Should I file a PR?

**Comment by MrAlias** [comment]
@skonto thanks for the question. At this time we are focusing on delivering a 1.0.0 release candidate that will implement the 1.0.1 release of the OpenTelemetry specification. This work is centered on tracing and context propagation, but it does not include metrics. For that reason this is not something we will be prioritizing at this time. Especially since there is large effort in the OpenTelemetry project to overhaul the metric signal implementation.

**Comment by MrAlias** [comment]
@skonto FWIW, the specification defines resources as immutable types and states their association with providers as being constant. We'll need to wait for the metric specification to solidify before we can make changes to how the controller handles this association.

**Comment by skonto** [comment]
@MrAlias thank you. I am interested in this because we have this requirement at knative monitoring. I am doing a [spike](https://github.com/knative/eventing/issues/4769) to see if we can migrate to this new lib.

**Comment by skonto** [comment]
@MrAlias 
> FWIW, the specification defines resources as immutable types and states their association with providers as being constant. 

I am looking for a way to associate N resources with a controller and dynamically de-associate them from it. Is there a pointer for the requirements captured by Metric SIG, I would like to provide feedback about this use case.
![image](https://user-images.githubusercontent.com/7945591/113287006-a0f53780-92f5-11eb-8b48-bc4239955511.png)

**Comment by MrAlias** [comment]
@skonto I think it would be worth attending the metric SIG meetings or maybe posting in the [slack channel](https://cloud-native.slack.com/archives/C01NP3BV26R).

The merging of multiple resource into a single one is currently supported with the [`Merge`](https://github.com/open-telemetry/opentelemetry-go/blob/23422c56df5578ae4f70f8bd5c0225dbad6be388/sdk/resource/resource.go#L114) function, but, by design, association with a controller is static.

**Comment by MrAlias** [comment]
@skonto can this be closed?

The association of a resource to a `MeterProvider` is going to be a static one-to-one relationship based on the [OTel specification definition](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#meterprovider). If multiple resources are needed a dynamic way to change out `MeterProvider`s is likely something you will need to develop.

**Comment by MrAlias** [comment]
Closing as this looks stale. Please re-open if this was an error.
