### ISSUE TITLE
SDK should support an error callback

### ISSUE THREAD

**Issue by dmathieu** [open-telemetry/opentelemetry-go#174]
As mentioned in https://github.com/open-telemetry/opentelemetry-go/pull/162#discussion_r332183065

**Comment by jmacd** [comment]
The SDK itself also should support an `OnError()` callback so that it can issue errors to a handler configured by the application `main()` function. Probably every component (SDK, processor, exporter) should support this in a uniform way.

**Comment by akvanhar** [comment]
If this is something we expect exporters to handle in a uniform way, does it make sense to have it implemented here instead? A default `OnError()` call back could do `log.Printf("Error when uploading spans to Exporter: %v", err)`. Even better if we know the name of the exporter in question.

**Comment by jmacd** [comment]
Discussed in the weekly SIG meeting. We support the idea of an interface with an `OnError` method that is passed to the constructors of each SDK, processor, exporter, and plugin that might need to report errors.

**Comment by freeformz** [comment]
@jmacd Do you mean an optional interface, such that the sdk checks to see if an exporter or the like is also an `OnErrorer` or the like and if so then uses this? Or something else?

**Comment by jmacd** [comment]
To me there are two questions here.
Should each connected group of SDK/processor/exporter/plugin share a single `OnError` handler? (If yes, how is this organized?)
Should there be a global `OnError` handler? (If no, will there be conditions where there's not a well defined `OnError` handler?)
One approach would be to have the SDK implement an `OnError` handler, and let the pre-initialization global SDK have a sensible default. This is slightly complicated because the exporter and processors are going to be constructed before the SDK. Should we somehow make the `OnError` handler a (standard, functional) option passed to all components?

Another trouble with this idea is that we haven't specified a type for the "SDK" itself. At present all we have are the idea of a `Tracer` and `Meter` factory (for named tracers and meters) plus the standing OTEP 0005 about global initialization:  https://github.com/open-telemetry/oteps/pull/45/files

**Comment by jmacd** [comment]
I suggest this issue be named "SDK should to support an error callback". The current default metrics SDK supports one, but it should be supported by the tracer SDK as well.

**Comment by MrAlias** [comment]
Possibly worth looking into adding a `global` error handler (to be useful prior to sdk registration).
