### ISSUE TITLE
Possible bug in otlpgrpc exporter

### ISSUE THREAD

**Issue by imle** [open-telemetry/opentelemetry-go#1756]
In the `example/otel-collector`, I think I have come across a strange bug that only occurs with a ver specific set of `Option` specified.

I figured this out while debugging the issue with that example, which is that the k8s resource's ports don't line up (wrong port in config compared to README and to Deployment).

When specifying the `WithInsecure`, `WithEndpoint`, and `WithDialOption(WithBlock)` for the driver, the code will hang forever on the call to `NewExporter` unless the endpoint is correct and reachable. Without `WithInsecure`, the code will return immediately even though the same incorrect/unreachable endpoint was used. Passing a context with a timeout mitigates this, but the result is not an error, it is an object without a valid connection that is never able to resolve its connection.

Example code below:
```go
driver := otlpgrpc.NewDriver(
	otlpgrpc.WithInsecure(),
	otlpgrpc.WithEndpoint("localhost:30080"),
	otlpgrpc.WithDialOption(grpc.WithBlock()), // useful for testing
)

driver := otlpgrpc.NewDriver(options...)

exp, err := otlp.NewExporter(ctx, driver)
```

To be honest, I am not sure what the correct behavior is here, but one of these cases appears wrong.

**Environment:**
go: v1.16.2
os: macOS 11.2.3

**Comment by MadVikingGod** [comment]
That is what the `WithBlock()` is intended to do.  When you use `WithBlock` the connection is established synchronously, and it does not have a default timeout.  You can add one either with a `context.WithTimeout` for the initial connection, or a `grpc.WithTimeout()` for all connection attempts.

We should maybe consider adding some kind of default timeout.

**Comment by imle** [comment]
I hate to reopen this, but just for clarification, the issue was that the behavior would change when `WithInsecure` is present.

The below case blocks.
```go
driver := otlpgrpc.NewDriver(
	otlpgrpc.WithInsecure(),
	otlpgrpc.WithEndpoint("localhost:30080"),
	otlpgrpc.WithDialOption(grpc.WithBlock()), // useful for testing
)
```

This case does not.
```go
driver := otlpgrpc.NewDriver(
	otlpgrpc.WithEndpoint("localhost:30080"),
	otlpgrpc.WithDialOption(grpc.WithBlock()), // useful for testing
)
```

**Comment by MadVikingGod** [comment]
You are right.  It does this because the underlying GRPC client immediately returns with an error, and our code [is silently consuming that error](https://github.com/open-telemetry/opentelemetry-go/blob/c5d006c07ab78e6b21690e86c859e5f6752d0086/exporters/otlp/otlpgrpc/connection.go#L72-L77)

So at a bare minimum, I think we need to report his error to our error handler.  
I haven't thought through the implications of passing that error through.  It would in this case solve the issue, but it would also prevent `otlp.NewExporter()` from creating an exporter on any error.  I think this is ok, but I will need to experiment with it.

The grpc error in this case is:
> "grpc: no transport security set (use grpc.WithInsecure() explicitly or set credentials)"
