### ISSUE TITLE
Unable to manually set timestamp on metrics leads to wrong behaviour when using message busses (e.g. Kafka)

### ISSUE THREAD

**Issue by ConverJens** [open-telemetry/opentelemetry-go#1861]
### Description

It is currently not possible to set timestamp on metrics. This means that when exporting data points from a  message bus (e.g. Kafka), the timestamp is not correct.

### Environment

- OS: ubuntu 20.04
- Architecture:  x86
- Go Version: 1.16
- opentelemetry-go version:  v0.20.0

### Steps To Reproduce

1. Use the configuration '...'
2. Run '...'
3. See error

### Expected behavior

An option on the instrument to manually set the measurement timestamp.

**Comment by Aneurysm9** [comment]
Could you describe your use case a bit more?  It sounds like you're looking to take metric samples that had been observed elsewhere from a message bus and emit them through the SDK to some downstream receiver.  Might that not be a better fit for the Collector?

**Comment by ConverJens** [comment]
Hi @Aneurysm9,

Thank you for your response!

> Could you describe your use case a bit more? It sounds like you're looking to take metric samples that had been observed elsewhere from a message bus and emit them through the SDK to some downstream receiver. Might that not be a better fit for the Collector?

This is close but not quite what I'm trying to do. 

I have data points (protobufs) generated upstreams that I process and build metrics from. What I need is to preserve the timestamp on the original data point.

More in detail, the upstream process is actually a pipeline which takes a trace span, enriches it with output from a machine learning model which is now to be post-processed.

The data is propagated several steps with message busses acting as buffers in between.

**Comment by MrAlias** [comment]
Thanks for opening the issue. The situations described does not sound like one this project is looking to solve. This project provides an API used to directly instrument code and an SDK to implement that API and send measurements to a remote location.

The transformation and re-transmission of already captured data describes the purpose of [the OpenTelemetry collector](https://github.com/open-telemetry/opentelemetry-collector). I would recommend giving that a look. Otherwise, it sounds like the translation you are looking to perform might be easy enough to just manually do yourself by directly working with the [OTLP](https://github.com/open-telemetry/opentelemetry-proto) (if you are interested in doing this in Go we have [a generated codebase](https://github.com/open-telemetry/opentelemetry-proto-go) for this).

**Comment by ZackingIt** [comment]
@ConverJens  did you find a different solution to this issue with the OpenTelemetry collector / another approach?  We have the exact same concern around needing to manually set timestamps due to using a message bus for data points.

**Comment by ConverJens** [comment]
@ZackingIt Sorry for the late response.

In essence, the OTEL metric spec doesn't support this use-case and so, no OTEL implementation will either.

I resorted to using Prometheus python client where I was able to finally fix this by implementing a custom collector. This was quite straight-forward and didn't take very long (a few days) if I recall correctly.
