### ISSUE TITLE
Can't set Jaeger's process Tag fields - `key`  and `value` are not exported

### ISSUE THREAD

**Issue by cirocosta** [open-telemetry/opentelemetry-go#202]
Hi!

First of all, thanks for all of your hard work!

I noticed that when https://github.com/open-telemetry/opentelemetry-go/pull/112 was submitted, during the review pass, `Tag` constructors were dropped, but it seems like no other public way for constructing `jaeger.Tag` was left.

https://github.com/open-telemetry/opentelemetry-go/blob/3516ebc456c7ce437d6c12071e44d90b029fc2aa/exporter/trace/jaeger/jaeger.go#L132-L137

Am I missing something?

Thank you!

**Comment by jmacd** [comment]
I suspect this was unintentional. Let's restore the `Tag` constructor.  Perhaps we should move `jaeger_test.go` into a separate package to be sure it can't use unexported fields.

**Comment by paivagustavo** [comment]
I would like to help on this one @jmacd, is it okay?

I saw that there is a to do in the `attributeToTag` method pointing to the fact that we're using `interface{}`.  I think that this could be fixed together.

I see two options to this problem:

1.  We could use the value OpenTelemetry core.KeyValue instead of defining another struct that has the same objective and convert it to the jaeger tag.

Something along:
```go
	// Create Jaeger Exporter
	exporter, err := jaeger.NewExporter(
		jaeger.WithCollectorEndpoint("http://localhost:14268/api/traces"),
		jaeger.WithProcess(jaeger.Process{
			ServiceName: "trace-demo",
			Tags: []core.KeyValue{core.Key{"key"}.String("value")},
		}),
	)
```
I like this approach more because it bring conformity to the OpenTelemetry libs overall.

2. Export methods to create jaeger.Tag directly to the user. Something like:
```go
import (
	"go.opentelemetry.io/exporter/trace/jaeger"
	gen "go.opentelemetry.io/exporter/trace/jaeger/internal/gen-go/jaeger"
)
...
	exporter, err := jaeger.NewExporter(
		jaeger.WithCollectorEndpoint("http://localhost:14268/api/traces"),
		jaeger.WithProcess(jaeger.Process{
			ServiceName: "trace-demo",
			Tags: []gen.Tag{jaeger.StringTag("key", "value")},
		}),
	)
```
But I found this confusing to the user, because they would import two packages with the same name and be forced to name one of then.

**Comment by jmacd** [comment]
I prefer the first option. :)
