### ISSUE TITLE
HTTP propagator names should use "HTTP" instead of "Http"

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#208]
Renaming these would make them consistent with [Go's recommended naming](https://github.com/golang/go/wiki/CodeReviewComments#initialisms).

**Comment by freeformz** [comment]
if no one else is interested, feel free to assign this to me.

**Comment by jmacd** [comment]
@matej-g please go ahead. (@freeformz I've assigned a couple of others to you already today.) :)

**Comment by matej-g** [comment]
So it seems it has just been done by https://github.com/open-telemetry/opentelemetry-go/pull/214 , apart from couple of test function names (still could do that if this issue is still valid). I also noticed there are some other initialisms in parts of the codebase not adhering to the styling guide (mostly "Url"), not sure whether fixing those could be also of interest?

**Comment by iredelmeier** [comment]
@matej-g fixing `Url` and other initialisms would indeed be of interest!

**Comment by freeformz** [comment]
@matej-g Sorry. I forgot that you were interested in this. I only did the HTTP ones because the linter was complaining and I needed to fix them to get things to pass.

**Comment by rghetia** [comment]
@rghetia  to check if this should be closed.

**Comment by matej-g** [comment]
Thanks for the encouragement, I opened https://github.com/open-telemetry/opentelemetry-go/pull/220 with some minor fixes.

I've seen there has been a lot of `good first issue` labels added, I would be happy to contribute more. Without getting too much off-topic, any suggestion on which issue(s) I could tackle next?
