### ISSUE TITLE
Suggestion: core.Key should be a type alias instead of struct

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#209]
Making [`core.Key`](https://github.com/open-telemetry/opentelemetry-go/blob/e0eccc9a57e0cae76c1c5b0dde747bb79a8f1300/api/core/key.go#L8-L10) a type alias for `string` instead of a whole struct would (arguably!) make it easier to use, while still allowing us to add methods on `Key`.

**Comment by jmacd** [comment]
Sounds good. I see no objections. The original type was a struct and had some of the fields it could theoretically share w/ a metric, like having a description or units. That was removed and there's no reason to leave a struct behind.

**Comment by paivagustavo** [comment]
Could we take this issue and improve the creation of a KeyValue as well?

Currently, to create a KeyValue we need to do: `key.New("k1").String("v1")`. I would like to propose us to change to `key.String("k1","v1")`,  `key.Int64("k2", 123)`, `key.Bool("k3", true)` and etc.

If we are going to drop the struct, why do we need the `key` type alias at all? Couldn't we just simplify the `KeyValue` struct to?
```go
type KeyValue struct {
	Key   string
	Value Value
}
```

**Comment by jmacd** [comment]
We would like people to be able to statically declare typed keys. As in

```
const (
   aVeryImportantKey core.Key = "a_very_important_key".
)
```

In a large code base, this is important to ensure that keys are not misspelled in various parts of the code.  I do not oppose the idea of offering helpers to construct keys using bare strings, but I think bare-string keys are not a scalable practice in software.

**Comment by paivagustavo** [comment]
I get the use case now of the type alias now.

I agree that most of the cases the usage `keyName.Type(value)` is the best, since the key between multiples executions is going to be the same. But when creating a KeyValue that is going to be used a single time, e.g. constructor of exporter like jaeger (#202), `key.Type(Name, Value)` seems better.

In the end, I'll change the struct to a type alias and add this new KeyValue helpers since there is no opposition.
