### ISSUE TITLE
Proposal: Use goyek for build automation

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#2152]
### Problem Statement

Right now, the automation pipelines are build of:

- `Makefile`
- Bash scripts `tag.sh`, `pre_release.sh`, `get_main_pkgs.sh`, `verify_examples.sh`
- Internal Go CLI apps: `internal/tools/crosslink` and `internal/tools/semconv-gen`
- Common OTel Go CLI apps from https://github.com/open-telemetry/opentelemetry-go-build-tools (not currently used in this repository)

Some problems:

1. **Maintainability.** It requires to know not only Go, but also Bash and Make quite well.
1. **Reusability.** While the Go CLI apps can be easily reused between the repositories, this cannot be said for `Makefile` or Bash scripts.
1. **Portability.** The current build pipeline does not work properly on Windows. And creating Bash scripts and `Makefile` that work properly on Windows (e.g. via MinGW) is not always simple.

### Proposed Solution

Use [`goyek`](https://github.com/goyek/goyek) instead of Makefile. The approach is inspired by tools like:

- https://ruby.github.io/rake/
- https://cakebuild.net/ 
- https://github.com/adamralph/bullseye
- https://nuke.build/

We could register [`goyek.Task`](https://pkg.go.dev/github.com/goyek/goyek#Task) instead of writing bash scripts and internal Go CLI Apps.
Writing task's implementation (action) reminds writing a unit test using the `testing` package.

Reusability between repositories should be easier as well thanks to Go Modules. We could choose from:

- Reusing common Go functions.
- Reusing Tasks implementation.
- Reusing common workflows/pipelines.

#### Alternatives

[Mage](https://magefile.org/) was created to solve the same issue. It is more widely used and has a larger community.

However, personally, I do not like its design. Why? See: [here](https://github.com/goyek/goyek/blob/main/docs/alternatives.md#mage).

#### Prior Art

Here is a sample repository containing a common build pipeline: <https://github.com/signalfx/go-pipeline>.

Here is a PR to demonstrate how transitioning from the current approach could look like: <https://github.com/signalfx/splunk-otel-go/pull/71> (there is even a recorded 2.5 min demo).

### Additional Context

The proposal is opinionated as I am the creator of [`goyek`](https://github.com/goyek/goyek).

I have created this proposal after seeing <https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/8>.

**Comment by eddyleelin** [comment]
Context: I am the author of the [PR linked from OpenTelemetry-Go-Build-Tools](https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/8). 

This looks awesome and would definitely help to unify a lot of aspects of the build tools! I liked the demo, and it seems like rewriting an internal Go CLI app to use Goyek be rather straightforward? Would definitely be interested in integrating/deploying the Go MultiMod releaser tool with Goyek in the coming weeks.

**Comment by Aneurysm9** [comment]
I agree with @eddyleelin that this looks like a potentially good thing for some of the tooling we've built, but I'd draw the line at attempting to replace Make with it.  I think the [goyek docs](https://github.com/goyek/goyek/blob/main/docs/alternatives.md#make) cover our scenario pretty clearly:

> However, if you know Make and are happy with it, do not change it. Make is very powerful and a lot of stuff can be made faster, if you know how to use it.

We've already got working `Makefile`s that meet our needs and I'm not sure I see us outgrowing Make any time soon.

**Comment by pellared** [comment]
> We've already got working Makefiles that meet our needs and I'm not sure I see us outgrowing Make any time soon.

Fair. I am good to close this issue. Even if I would be the one to reimplement - I think it would be far more valuable if I make more code reviews instead 😉

**Comment by sagikazarmark** [comment]
A couple random thoughts (without any intent to argue pro/contra goyek itself):

Wouldn't replacing Shell with a different _framework_ (even if it's syntactically Go code) yield the same problem? I mean, people having to learn shell and having to learn using a framework doesn't seem very different to me. Not to mention that Shell is probably more useful knowledge anyway.

I would also argue that not everyone has to be intimately familiar with all of the tools and how they are constructed. They need to be easy to use first IMO.

If there is a need, there are generic build systems (Bazel, Please, etc) that might be worth to check out as well. On that note: [Kubernetes](https://github.com/kubernetes/enhancements/issues/2420) and [Istio](https://twitter.com/kelseyhightower/status/958834738650755072) seem to be in the process of getting rid of Bazel in order to lower the entry barrier for contributing to those projects. So adding another tool to the mix is not necessarily the best solution.

Instead of picking the tool to unify the different build tasks, I would probably close from a "customer" angle to the problem: who uses these tools? who needs to maintain them? Simplify things for the larger user base (eg. standardize on a Make based interface for contributors, maybe even for release managers). Then the underlying implementation won't matter: it can be goyak if that simplifies the maintenance, but my guess is editing those scripts now and then is not that serious of a problem.

My two cents.

**Comment by pellared** [comment]
The only problem for me so far was that currently, not everything works fine on Windows. Making things working on *NIX + Windows is for me easier in Go than in Bash+Make 😉 But it can be for sure fixed using Bash and Make as well with things like `pwd -W` on Windows. Closing.
