### ISSUE TITLE
Opentelemetry exporter is slow

### ISSUE THREAD

**Issue by itziklavon** [open-telemetry/opentelemetry-go#2198]
Hi, i'm trying to export traces using the exporter, when load is high(±1k traces per second), i'm getting timeout error, or that client is disconnected, used grpc client for exporting and batch exporter configuration, however, seems like it does not help much, how can i improve it?

this is my current code(pertty much the same as you have in the example):
```
	traceExporter, err := otlptracegrpc.New(context.Background(),
		otlptracegrpc.WithInsecure(),
		otlptracegrpc.WithDialOption(grpc.WithBlock()),
		otlptracegrpc.WithEndpoint("localhost:4317"),
		otlptracegrpc.WithRetry(otlptracegrpc.RetryConfig{
			Enabled:         true,
			InitialInterval: 1 * time.Second,
			MaxInterval:     5 * time.Second,
			MaxElapsedTime:  10 * time.Minute,
		},
		),
	)

	if err != nil {
		panic(err)
	}
	resources, err := resource.New(
		context.Background(),
		resource.WithAttributes(
			attribute.String("service.name", "wazdan"),
		),
	)
	if err != nil {
		panic(err)
	}
	//
	bsp := sdktrace.NewBatchSpanProcessor(traceExporter)

	otel.SetTracerProvider(
		sdktrace.NewTracerProvider(
			sdktrace.WithSampler(sdktrace.AlwaysSample()),
			sdktrace.WithSpanProcessor(bsp),
			sdktrace.WithResource(resources),
		),
	)

**Comment by MrAlias** [comment]
Based on the description you gave it sounds like you are overloading your network or the receiver. It will likely be helpful for you in this troubleshooting to make sure you understand where this is ultimately being bottlenecked. From there you can look at tuning the batch span processor if the setup/teardown of communication is limiting you. Otherwise, you will need to look at your sampling strategy. Sampling everything is usually something that is helpful for demonstration, but often causes failure like what you are seeing in production systems. You can take a look at the [`ParentBased`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/trace#ParentBased) sampler in conjunction with the [`TraceIDRatioBased`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/trace#TraceIDRatioBased).

I hope this helps. I'm going to close this issue does not track something we need to address in the code. Please open an issue if you do find something we need to address in the code, and it might be helpful to chat with the community in our [slack channel](https://cloud-native.slack.com/archives/C01NPAXACKT).
