### ISSUE TITLE
Support the OTEL_TRACES_EXPORTER environment variable

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2310]
Add support for the `OTEL_TRACES_EXPORTER` environment variable as defined in the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/sdk-environment-variables.md#exporter-selection).

This will require designing and ratifying a plan to support loading all the exporters we need without having the SDK import them all. As was mentioned [here](https://github.com/open-telemetry/opentelemetry-go/issues/1698#issuecomment-946885975) we could look at the https://pkg.go.dev/plugin package. Or, as was suggested in a SIG meeting, look into maybe some registration method similar to the `database/sql` package.

It might also be the case that we do not want to ultimately support this. Part of this issue is determining the feasibility and appropriateness of this configuration option.

Part of #1698

**Comment by MovieStoreGuy** [comment]
@MrAlias , moving to the  https://pkg.go.dev/plugin requires that applications ship with cgo enabled since it depends on the c method `dlopen`. This could be problematic for services that ship a static binary into their production environment. I believe this to be the common case for most golang based applications.

Is it permissible to have environment variable defined, but only consumed if the application developer adds in the exporter explicitly? 

for example:

```golang
import (
     otel/sdk
     otel/exporter
     _ otel/exporter/zipkin // registering global init method to allow for zipkin exporter
)

// Carrying on, start the SDK and have a valid, configured zipkin exporter
```

```golang
import (
    otel/sdk
    otel/exporter
    _ otel/exporter/otlp
)

// zipkin var is present but no zipkin exporter configured
```

**Comment by pellared** [comment]
> look into maybe some registration method similar to the database/sql package

I see it as the best approach as

1. it does not force any dependencies
2. it gives the possibility to select the propagators that are supported by the application
3. it allows also building a convenience module/package that will contain the propagators that should be supported by the spec (`tracecontext` and `baggage`)
4. I find it good when we can reuse a pattern used in the standard library

https://pkg.go.dev/plugin is rather a no-go as it does even not work on all platforms. I find it also not suitable for this use case.

FYI this is something I plan to do in .NET SDK: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1453#issuecomment-858454790

**Comment by pellared** [comment]
I mean "we should only include the required exporter code (say .../pkg/zipkin) when explicitly asked to".

**Comment by MrAlias** [comment]
Should be resolved by https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2753

**Comment by pellared** [comment]
I think that the env var should be supported by the SDK (`sdk/trace` package).

Reference: https://github.com/open-telemetry/opentelemetry-specification/issues/3721#issuecomment-1761995814

**Comment by pellared** [comment]
On hold. See https://github.com/open-telemetry/opentelemetry-specification/issues/3721#issuecomment-1771553380

**Comment by pellared** [comment]
Closing per https://github.com/open-telemetry/opentelemetry-specification/pull/3730

**Comment by ringerc** [comment]
IMO this should at least emit a warning (or debug log) when `OTEL_TRACES_EXPORTER` is configured in the environment but ignored by the SDK setup.

See https://github.com/open-telemetry/opentelemetry-go/issues/7940

The docs also need _prominent_ warnings that these are not supported. It's particularly confusing because the go sdk docs refer to _other_ parts of the exporter configuration from environment variables in the main env-vars spec, but nothing clearly specifies which env-vars are / are not supported by the go SDK.
