### ISSUE TITLE
when use ContextWithSpanContext(ctx,sc),no trace log generated

### ISSUE THREAD

**Issue by itmisx** [open-telemetry/opentelemetry-go#2434]
### Description

when use the context.Background(),trace log is ok. but when use the context  created by ContextWithSpanContext(ctx,sc),no trace log generated

### Environment

- Architecture: [e.g. x86, i386]
- Go Version: [e.g. 1.15]
- opentelemetry-go version: [e.g. v0.14.0, 3c7face]

### Steps To Reproduce

```go
	tp, err := fileExporter()
	if err != nil {
		log.Fatal(err)
	}

	otel.SetTracerProvider(tp)

	ctx := context.Background()
	sc := oteltrace.NewSpanContext(oteltrace.SpanContextConfig{
		TraceID: oteltrace.TraceID{0x01},
		SpanID:  oteltrace.SpanID{0x01},
	})
	ctx = oteltrace.ContextWithRemoteSpanContext(ctx, sc)

	tr := tp.Tracer("")

	ctx, span := tr.Start(ctx, "foo")
	span.RecordError(errors.New("foo err"))
	span.AddEvent("lock")
	span.AddEvent("unlock")
	span.End()

	tp.Shutdown(ctx)
```

### Expected behavior

i hope i can create context by traceID

**Comment by MrAlias** [comment]
Please add your environment information and a complete example including the received output. It is not clear to me what issue you are experiencing.

**Comment by itmisx** [comment]
below is the golang code,I want to use my own traceID, but the generated trace.txt content is empty.
```golang
package main

import (
	"context"
	"errors"
	"io"
	"log"
	"os"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/exporters/stdout/stdouttrace"
	"go.opentelemetry.io/otel/sdk/trace"
	oteltrace "go.opentelemetry.io/otel/trace"
)

func main() {
	tp, err := fileExporter()
	if err != nil {
		log.Fatal(err)
	}

	otel.SetTracerProvider(tp)

	ctx := context.Background()
	sc := oteltrace.NewSpanContext(oteltrace.SpanContextConfig{
		TraceID: oteltrace.TraceID{0x01},
		SpanID:  oteltrace.SpanID{0x01},
	})
	ctx = oteltrace.ContextWithRemoteSpanContext(ctx, sc)

	tr := tp.Tracer("")

	ctx, span := tr.Start(ctx, "foo")
	span.RecordError(errors.New("foo err"))
	span.AddEvent("lock")
	span.AddEvent("unlock")
	span.End()

	tp.Shutdown(ctx)
}

func fileExporter() (*trace.TracerProvider, error) {
	l := log.New(os.Stdout, "", 0)

	f, err := os.Create("traces.txt")
	if err != nil {
		l.Fatal(err)
	}

	exp, err := newExporter(f)
	if err != nil {
		l.Fatal(err)
	}

	tp := trace.NewTracerProvider(
		trace.WithBatcher(exp),
	)
	return tp, nil
}

func newExporter(w io.Writer) (trace.SpanExporter, error) {
	return stdouttrace.New(
		stdouttrace.WithWriter(w),
		stdouttrace.WithPrettyPrint(),
		stdouttrace.WithoutTimestamps(),
	)
}
```

**Comment by MrAlias** [comment]
Both `ContextWithRemoteSpanContext` and `ContextWithSpanContext` will wrap a `SpanContext` in a non-recording span, [as per the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/a6cfbc92d36aa019c95fc2d9f023f5de5d570937/specification/trace/api.md#wrapping-a-spancontext-in-a-span). This means that any children of that span will also be non-recording and, [as specified](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.8.0/specification/trace/sdk.md#sampling), the span exporter/processor does not receive the span.

You can make the child span a root with the `WithNewRoot` option. This will potentially set the span as recording based on your sampling decision.

```go
	ctx, span := tr.Start(ctx, "foo", oteltrace.WithNewRoot())
```

Otherwise, you will need to [register](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.3.0/trace#WithSampler) your own [`Sampler`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.3.0/trace#Sampler) that overrides the OpenTelemetry default behavior.

**Comment by itmisx** [comment]
> Thanks for the updated example. Both `ContextWithRemoteSpanContext` and `ContextWithSpanContext` will wrap a `SpanContext` in a non-recording span, [as per the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/a6cfbc92d36aa019c95fc2d9f023f5de5d570937/specification/trace/api.md#wrapping-a-spancontext-in-a-span). This means that any children of that span will also be non-recording and, [as specified](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.8.0/specification/trace/sdk.md#sampling), the span exporter/processor does not receive the span.
> 
> You can make the child span a root with the `WithNewRoot` option. This will potentially set the span as recording based on your sampling decision.
> 
> ```go
> 	ctx, span := tr.Start(ctx, "foo", oteltrace.WithNewRoot())
> ```
> 
> Otherwise, you will need to [register](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.3.0/trace#WithSampler) your own [`Sampler`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.3.0/trace#Sampler) that overrides the OpenTelemetry default behavior.

Thank you very much for your answer
