### ISSUE TITLE
Migrating from opentracing Jaeger to opentelemetry 

### ISSUE THREAD

**Issue by dino-ma** [open-telemetry/opentelemetry-go#2642]
I'd like to ask how to set probability sampling through opentelemetry. Previously, it was implemented through Jaeger's collector configuration by the client to request the interface of the agent. Now, opentelemetry will automatically implement this strategy. Don't we need to configure the service name and URL address?

And where can Jaeger's bufferflush interval be set?

**Comment by dino-ma** [comment]
jaegerConfig.ReporterConfig.BufferFlushInterval
jaegerConfig.SamplerConfig.SamplingServerURL

**Comment by dmathieu** [comment]
When using [BatchSpanProcessor](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/batch_span_processor.go), you can specify a `WithMaxQueueSize` option which would be the rough equivalent of `BufferFlushInterval`.
The processor relies on the size of the queue instead of intervals. But the effect can be similar.

As for sampling, you can specify a sampler when creating the tracer provider. See this example: https://github.com/open-telemetry/opentelemetry-go/blob/main/example/namedtracer/main.go#L50
If your stack includes the collector, you may also do sampling at that level using the [probabilistic sampler](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/probabilisticsamplerprocessor).

**Comment by dino-ma** [comment]
> jaegerConfig.ReporterConfig.BufferFlushInterval

jaegerConfig. ReporterConfig. BufferFlushInterval

This is OK. I can accept it

However, I want to set the sampling rules through the remote collector instead of the default setting in the SDK.

**Comment by dmathieu** [comment]
You can do that with one of the included samplers (such as the probalistic one linked above) in opentelemetry-collector-contrib, or by writing your own.

**Comment by dino-ma** [comment]
In the future, do we plan to limit current through the remote like Jaeger

`{
  "service_strategies": [
    {
      "service": "live",
      "type": "probabilistic",
      "param": 0.01,
      "operation_strategies": [
        {
          "operation": "Kylin Rpc Server/v1/selfpage/brand",
          "type": "probabilistic",
          "param": 0.01
        },
        {
          "operation": "Kylin Rpc Server/v1/selfpage/feed",
          "type": "probabilistic",
          "param": 0.01
        }
      ]
    },
    {
      "service": "hoegaarden",
      "type": "probabilistic",
      "param": 0.1
    }
  ],
  "default_strategy": {
    "type": "probabilistic",
    "param": 0.5,
    "operation_strategies": [
      {
        "operation": "/metrics",
        "type": "probabilistic",
        "param": 0.0
      },
      {
        "operation": "Kylin Rpc Server/metrics",
        "type": "probabilistic",
        "param": 0.0
      }
    ]
  }
}`

**Comment by dmathieu** [comment]
I think questions specific to the collector and its configuration would probably be better answered in the [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector) repository.

**Comment by dino-ma** [comment]
Can this [PR](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/936/files) be merged?

**Comment by MrAlias** [comment]
Closing because https://github.com/open-telemetry/opentelemetry-go-contrib/pull/936 has been merged. Please reopen if this was in error.
