### ISSUE TITLE
Rename (p NoopProvider) GetTracer to (p NoopProvider) NewTracer 

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#301]
GetTracer is actually constructing a new Tracer hence should be called NewTracer.

**Comment by jmacd** [comment]
@iredelmeier has said the same thing. :)

**Comment by iredelmeier** [comment]
Yeah, I brought this up internally the other day :)

**Comment by paivagustavo** [comment]
From the Named Tracer OTEP, Providers should be a "get or create". So renaming this to `NewTracer()` would not be the best option and renaming to `GetOrCreateTracer()` feels weird.

I would say we need to improve docs here.

**Comment by jmacd** [comment]
I don't like "OrCreate" in the name, because it implies a behavior that is not part of the semantics of the API. A valid SDK could not create anything as a result of this call, at least as far as the current specification stands (see related discussion about why "Registry" is not a good name in the Gitter https://gitter.im/open-telemetry/language-agnostic-wg).
