### ISSUE TITLE
Adding a View seems very strange, not clear ownership

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#3210]
Right now you can configure `Aggregation` into few places:
* Default aggregation in the `Reader`.
* Views when configured the `Reader` into the `MeterProvider`

An idea would be to make `Reader` owner of all the "aggregation selection" and register Views into the `Reader`. That way the we have a clear owner for this.

This is food for thought, but when trying to use the API I got confused about the two owners of aggregation selection.

**Comment by MrAlias** [comment]
I think this is a good idea, have the reader construction accept the views instead of the meter provider option. It would indeed be less confusing to the users.

We will need to check this confirms with the specification. I seem to remember that choice coming from the specification. But I'd need to verify.

**Comment by jmacd** [comment]
This design may have been inadvertently influenced by my prototype. See also https://github.com/open-telemetry/opentelemetry-specification/issues/2288

It makes sense to me to let each reader have their own view of the metrics, but actually the current specification says the view configuration is SDK-wide (which :shrug: to me defeats a lot of the value of the mechanism--I would recommend different views for pull and push-based configurations, for example).
