### ISSUE TITLE
Want support Semantic Versioning

### ISSUE THREAD

**Issue by 232136813** [open-telemetry/opentelemetry-go#3236]
### Problem Statement

Because opentelemetry-go do not support semantic versioning now, So we may encounter the conflict between otel 0.xx.xx and 1.xx.xx version, hope the official can support semantic version management

### Proposed Solution

support semantic versioning like this: module go.opentelemetry.io/otel/v1

**Comment by dmathieu** [comment]
We do follow semantic versioning across our versions. As you mention though, it's not set in the package's path, only in the version itself.
Your issue may be due to the fact that some packages were renamed/moved between 0.x and 1.x, and no deprecation releases were created.

Publishing those deprecation releases is in progress, and should be fixing this kind of issues.
See https://github.com/open-telemetry/opentelemetry-go/issues/2328

**Comment by MrAlias** [comment]
Why does something like the [go.opentelemetry.io/otel/semconv/v1.12.0](https://pkg.go.dev/go.opentelemetry.io/otel@v1.10.0/semconv/v1.12.0) package not solve your problem?

**Comment by MrAlias** [comment]
Closing as this looks stale. Please re-open if this was an error.
