### ISSUE TITLE
Unhandled 4XX errors in SpanStatusFromHTTPStatusCodeAndSpanKind

### ISSUE THREAD

**Issue by mehdihadeli** [open-telemetry/opentelemetry-go#3254]
Hi,
In the [SpanStatusFromHTTPStatusCodeAndSpanKind](https://github.com/open-telemetry/opentelemetry-go/blob/05c5509915fc2eca73d5c134d215274d47e157c5/semconv/internal/http.go#L307) method 4XX errors, doesn't set trace status to `Errors`! 
I saw in your code you skipped this range of errors, I think it should set trace status to `ERROR` instead of `UNSET`

**Comment by dmathieu** [comment]
This is actually the expected behavior, as described by the specification:
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#status

> For HTTP status codes in the 4xx range span status MUST be left unset in case of SpanKind.SERVER and MUST be set to Error in case of SpanKind.CLIENT.

This is because if your application returns a 4xx within a server span kind, it's expected that the status is set when the error is returned by the application itself.
Basically, when you set the 4xx status code in your code, you should also retrieve the HTTP span from the context and set its status appropriately.
