### ISSUE TITLE
Prometheus exporter reports reader not registered on startup

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3291]
### Description

Running the Prometheus exporter example results in the following error being logged:

```
reader is not registered
```

### Environment

- Go Version: 1.19
- opentelemetry-go version: b6a22abab751307b4851b3cc51728fa557f907bb

### Steps To Reproduce

1. Checkout commit
2. `cd example/prometheus`
3. `go run .`
4. See error:

```terminal
2022/10/14 13:23:14 reader is not registered
2022/10/14 13:23:14 serving metrics at localhost:2223/metrics
```

### Expected behavior

The line `2022/10/14 13:23:14 reader is not registered` should not be logged.

**Comment by MrAlias** [comment]
My guess is this error is returned by the underlying `manualReader` when the `collector` is registered. Likely because `Describe` is being called then and the exporter has not been registered with any `MeterProvider`.

Maybe this registration needs to be delayed?

**Comment by MadVikingGod** [comment]
After reading more details about the [prometheus collector interface](https://pkg.go.dev/github.com/prometheus/client_golang@v1.13.0/prometheus#hdr-Custom_Collectors_and_constant_Metrics) I think we should do nothing on Describe.  This is called when the collector is registered with prometheus, and is intended to produce the names of the metrics that we will send prometheus.  Because we won't know these until later, we should be using the unchecked collector mode of prometheus, by returning nothing.
