### ISSUE TITLE
bad jaeger tagged release

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/opentelemetry-go#331]
https://pkg.go.dev/mod/go.opentelemetry.io/otel/exporter/trace/jaeger@v1.0.0?tab=versions

we incorrectly created v1.0.0 on November 4 and now Go module proxy has cached it.

we should investigate whether we can get it purged.

**Comment by jmacd** [comment]
@marwan-at-work says this is permanently cached in the Go team's checksum database, which is a security mechanism for Go modules. We may have trouble re-using this tag.

**Comment by lizthegrey** [comment]
this also causes someone running `go get -u [...]` to pull the bad version as it's the "latest"...

**Comment by ferhatelmas** [comment]
Relevant issue - https://github.com/golang/go/issues/34189

I asked for the clarification of this case in a [comment](https://github.com/golang/go/issues/34189#issuecomment-561412668).

**Comment by lizthegrey** [comment]
https://github.com/golang/go/issues/24031 probably would resolve this issue by allowing us to badlist the v1.0.0 release.

**Comment by paivagustavo** [comment]
We should probably look for a workaround for this since there is no clear solution other than waiting for version v1.0.1 to come out. People are starting facing issues because of this. Some examples of the people that faced this:
- https://github.com/open-telemetry/opentelemetry-go/issues/470
- https://gitter.im/open-telemetry/community?at=5e41add23716b919ba0d5824

One possible solution that I have suggested on gitter is renaming the package, that should fix the problem.

**Comment by wingyplus** [comment]
@paivagustavo what’s about go get jaeger module with goproxy direct mode for now until this lib reach 1.0.0?

**Comment by lizthegrey** [comment]
agree renaming package makes good sense.

**Comment by MrAlias** [comment]
I'm planning to go with the suggestion made in the 2020-02-13 SIG meeting:

> Suggestion was to rename the “exporter” part of the URL to “exporters”. This would affect all the exporters, but given the alpha state it seemed reasonable.

Unless there is an alternate naming suggestion.

**Comment by lizthegrey** [comment]
Agree, good idea.
