### ISSUE TITLE
baggage member validation in ParseMember

### ISSUE THREAD

**Issue by FatemehRahmanzadeh** [open-telemetry/opentelemetry-go#3467]
Hi, I have an issue with extracting baggage header recived from node js service to my golang service.
my header contains not allowed characters like (semicolon, white space,...) but I did percent-encode them before injecting to headers...
my question is: W3C rules are checking in opentelemetry baggage package against member value after urlunscape the value.
But I think it must only check the baggage header value.
Are W3C rules also needed for baggage member inside service?
or just for transferring data between services?
I would appreciate any answer related to solve my problem.

**Comment by MrAlias** [comment]
You need to pass valid baggage members according to the W3C specification to `Baggage` because these are the members that will be transferred between services. The API is intentional.

Do you have an example of code that demonstrates the thing you are trying to achieve? Is there something you are not able to do with the current API?

**Comment by MrAlias** [comment]
Closing as this looks stale. Please re-open if this was an error.
