### ISSUE TITLE
Add `IsSampled` method to OpenTracing bridge

### ISSUE THREAD

**Issue by pijusn** [open-telemetry/opentelemetry-go#3532]
### Problem Statement

Bridge for OpenTracing does not expose whether span was picked for sampling.

### Proposed Solution

Add a method `bridgeSpanContext.IsSampled`.

### Additional Context

Ideally, this information would be exposed over OpenTracing interfaces but it's not (see https://github.com/opentracing/specification/issues/92 ). We work around it by invoking [Jaeger's `IsSampled`](https://github.com/jaegertracing/jaeger-client-go/blob/8d8e8fcfd04de42b8482476abac6a902fca47c18/span_context.go#L177-L181) directly. This information is used to optimize some of the critical paths.

I think it's not necessary to expose `bridgeSpanContext` all together. It would be enough to define a public `IsSampled` method that can be access by the few clients that want to have this information by casting it to a corresponding interface.

If you decide you are OK with the proposal, I should be able to make a PR for it.

**Comment by linasm** [comment]
@dmathieu (feel free to redirect me to someone else in case I've tagged a wrong person), are there any blockers for the suggested change (which already has a small PR with a possible implementation, https://github.com/open-telemetry/opentelemetry-go/pull/3570)?

**Comment by dmathieu** [comment]
Sorry, I didn't answer because I don't have enough context around the opentracing implementation to either +1 or object.
If you don't get an answer by then, I would recommend bringing this to a SIG meeting on thursdays. You can find the required information here: https://calendar.google.com/calendar/u/0/embed?src=google.com_b79e3e90j7bbsa2n2p5an5lf60@group.calendar.google.com
