### ISSUE TITLE
Generate a `service.instance.id` if it is not present?

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-go#3580]
Spec says https://github.com/open-telemetry/opentelemetry-specification/tree/v1.6.1/specification/resource/semantic_conventions#service

> MUST be unique for each instance of the same service.namespace,service.name pair (in other words service.namespace,service.name,service.instance.id triplet MUST be globally unique). The ID helps to distinguish instances of the same service that exist at the same time (e.g. instances of a horizontally scaled service). It is preferable for the ID to be persistent and stay the same for the lifetime of the service instance, however it is acceptable that the ID is ephemeral and changes during important lifetime events for the service (e.g. service restarts). If the service has no inherent unique ID that can be used as the value of this attribute it is recommended to generate a random Version 1 or Version 4 RFC 4122 UUID (services aiming for reproducible UUIDs may also use Version 5, see RFC 4122 for more recommendations).

Currently, builtin default Resource doesn't appear to do this. This is important for uniqueness and to ensure Prometheus exporters can disambiguate metrics. And for the single writer principle for [OTLP](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#single-writer).

**Comment by MrAlias** [comment]
Thanks for your interest in the project. The built-in default resource does not set the service namespace nor the ID. This is intentional. These are attributes the user of OTel is expected to define our their own. Having the OTel make this decision is not appropriate, it would impose on all users an ID they did not chose. Generating a service ID with the default resource is not something we plan to do.
