### ISSUE TITLE
Is there existing tool to convert "stdouttrace" output file to Jaeger's .json file? 

### ISSUE THREAD

**Issue by earthlovepython** [open-telemetry/opentelemetry-go#3588]
Hello, 

Is there existing tool to convert "stdouttrace" (https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/stdout/stdouttrace) output file to Jaeger's JSON file (https://github.com/jaegertracing/jaeger-ui/issues/381 has example .json file)? 

Thanks

**Comment by MrAlias** [comment]
Thanks for your interest in the project! There is not a tool hosted local to this project that does what you are asking and we do not plan to offer one. We do not want to give the impression the stdout export format should be considered a standard or even stable because it is not.

This does sound like an interesting 3rd-party utility that might have use by other users. If you decide to create and maintain your own, please be sure to register it with the OpenTelemetry [registry](https://opentelemetry.io/registry/).
