### ISSUE TITLE
Verify compliant metric SDK specification implementation: MetricExporter

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3665]
- [x] Identify all the normative requirements, recommendations, and options [the specification] defines as comments to this issue
- [ ] Ensure the [current metric SDK implementation] is compliant with these normative requirements, recommendations, and options in those comments.

[the specification]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md
[current metric SDK implementation]: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0

**Comment by MadVikingGod** [comment]
Requirements from reading the [Metric Exporter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricexporter) Section of the spec.  This doesn't cover The Push or Pull Subsections as different tickets cover them.

- MetricExporter is an interface that can be implemented outside the SDK.
  > MetricExporter defines the interface that protocol-specific exporters MUST implement so that they can be plugged into OpenTelemetry SDK and support sending of telemetry data.
- (Non-Normative) Metric Exporters always have an associated MetricReader.
  > Metric Exporters always have an associated MetricReader.
- (Non-Normative) The SDK uses the aggregation and temporality properties of the Metric Exporters
  > The aggregation and temporality properties used by the OpenTelemetry Metric SDK are determined when registering Metric Exporters through their associated MetricReader.
- (Optional) Automatic Configuration of metric Reader with an Exporter.
  > OpenTelemetry language implementations MAY support automatically configuring the MetricReader to use for an Exporter.
- Metric Exporters must have a way to report an error condition
  > Metric Exporters SHOULD report an error condition for data output by the `MetricReader` with unsupported Aggregation or Aggregation Temporality
- (Non-Normative) Multiple Exporters can be configured to on the same meter provider, using different MetricReaders.
  > There could be multiple Push Metric Exporters or Pull Metric Exporters or even a mixture of both configured at the same time on a given MeterProvider using one MetricReader for each exporter.

Note: The actual Interface of the MetricExporter is defined in the [Push Metric Exporter](https://github.com/open-telemetry/opentelemetry-go/issues/3666) Section.

**Comment by MadVikingGod** [comment]
Requirements from reading the [Push Metric Exporter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#push-metric-exporter) Section of the spec.

- Push Metric Exporter Interface Must have the following functions:
  - `Export`
    - > SDK MUST provide a way for the exporter to get the Meter information (e.g. name, version, etc.) associated with each Metric point.
    - > `Export` will never be called concurrently for the same exporter instance. `Export` can be called again only after the current call returns.
      - (Interpretation) Push Reader must not call `Export` concurrently.
    - > Export MUST NOT block indefinitely, there MUST be a reasonable upper limit after which the call must time out with an error result (Failure).
      - (Interpretation) There must be a cancellation mechanism for `Export`. Also there is no way to stop execution of an exporter that won't respect cancellation, this is a limitation of the language.
    - > The default SDK SHOULD NOT implement retry logic [around Export]
    - Export must accept a batch of Metric Points (this is language Dependant).
    - Export Must return `ExportResult` - Success or Failure
    
  - `ForceFlush`
    - > `ForceFlush` SHOULD provide a way to let the caller know whether it succeeded, failed or timed out.
    - > `ForceFlush` SHOULD only be called in cases where it is absolutely necessary, such as when using some FaaS providers that may suspend the process after an invocation, but before the exporter exports the completed metrics.
    - > `ForceFlush` SHOULD complete or abort within some timeout. ForceFlush can be implemented as a blocking API or an asynchronous API which notifies the caller via a callback or an event. 
    - (optional) flush timeout configurable.
  - `Shutdown`
    - > `Shutdown` SHOULD be called only once for each MetricExporter instance.
      - (Interpretation) Push Reader must call Shutdown on its Exporter
      - (Interpretation) Push Reader must not call Shutdown after it has been called once.
    - (Non-Normative) After the call to Shutdown subsequent calls to Export are not allowed and should return a Failure result.
    - Shutdown SHOULD NOT block indefinitely (e.g. if it attempts to flush the data and the destination is unavailable).
      - (Interpretation) There must be a cancellation mechanism for `Shutdown`. Also there is no way to stop execution of an exporter that won't respect cancellation, this is a limitation of the language.
    - (optional) shutdown timeout configurable.

Notes: 
Non-Normative means that there is a description in the spec but does not include normative vocabulary indicating requirements to the spec.

**Comment by MadVikingGod** [comment]
- MetricExporter is an interface that can be implemented outside the SDK. 
  - Done - [Exporter](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/metric/exporter.go#L31)
- Metric Exporters always have an associated MetricReader.
  - I don't think this is technically possible to enforce. To **always** have an associated Reader then they would the reader would have to be passed to the creation of the Exporter, but we do not control all constructors of Exporters (see above). This also would be inversion of the control flow, as Readers use Exporters, not the other way around.
  - A more generous interpretation is that the SDK will not use an Exporter except through a Reader, and we meet that requirement.
- The aggregation and temporality properties used by the OpenTelemetry Metric SDK are determined when registering Metric Exporters through their associated MetricReader.
  - The Aggregation and Temporality of a particular metric stream is somewhat complicated to determine, because it is a combination of the The View, and the Reader, and a default.
  - If the View does not [set the Aggregation here](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/metric/pipeline.go#L244), then the the stream will be check if the [exporter sets an aggregation](https://github.com/MadVikingGod/opentelemetry-go/blob/main/sdk/metric/pipeline.go#L313-L314)
  - Can a faulty Aggregation selector be passed to the Manual Reader?
  - Can a faulty Aggregation selector be passed to the Exporter?
- (Optional) Automatic Configuration of metric Reader with an Exporter.
  - We do not do this.
- Metric Exporters must have a way to report an error condition
  - Done - [Export](https://github.com/MadVikingGod/opentelemetry-go/blob/main/sdk/metric/exporter.go#L52-L53) returns an error that can be used for this.
- Multiple Exporters can be configured to on the same meter provider, using different MetricReaders.
  - Done - Use of multiple [WithReader](https://github.com/MadVikingGod/opentelemetry-go/blob/main/sdk/metric/config.go#L124-L125) options allows this.

The only task left open is the AggregationSelector and TemporalitySelector, to see if those can be abused.

**Comment by MrAlias** [comment]
Closing, done.
