### ISSUE TITLE
Verify compliant metric SDK specification implementation: MetricExporter/Pull Metric Exporter

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3667]
- [x] Identify all the normative requirements, recommendations, and options [the specification] defines as comments to this issue
- [x] Ensure the [current metric SDK implementation] is compliant with these normative requirements, recommendations, and options in those comments.

[the specification]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md
[current metric SDK implementation]: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0

**Comment by MadVikingGod** [comment]
Requirements from reading the [Pull Metric Exporter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#pull-metric-exporter) Section of the spec.

- > Implementors MAY choose the best idiomatic design for their language.
  - (Interpretation) Good Luck Y'all.
- > If the pull exporter is modeled as MetricReader, implementors MAY name the MetricExporter interface as `PushMetricExporter` to prevent naming confusion.
   - (Interpretation) We can call the Metric Exporter interface described in the [Push Metric Exporter](https://github.com/open-telemetry/opentelemetry-go/issues/3666) section as `PushMetricExporter`.

**Comment by MadVikingGod** [comment]
There isn't a Pull Metric Exporter defined in anyways in the Go SDK.  This interface between the ManualReader and the export format is left to the implementors of the Exporter to define and use.

The way the prometheus Exporter achieves this is by embedding a ManualReader in the Exporter type so that it can be registered in the SDK.  This embedded Reader.Collect() is used when prometheus starts gathering data points, and does the conversion to the prometheus format internal to the Exporter.  This interface would be different for a different kind of exporter but could use a similar pattern.

**Comment by MrAlias** [comment]
Looks good to me :+1:
