### ISSUE TITLE
Verify compliant metric SDK specification implementation: Compatibility requirements

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3671]
- [x] Identify all the normative requirements, recommendations, and options [the specification] defines as comments to this issue
- [x] Ensure the [current metric SDK implementation] is compliant with these normative requirements, recommendations, and options in those comments.

[the specification]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md
[current metric SDK implementation]: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0

**Comment by pellared** [comment]
> All the metrics components SHOULD allow new methods to be added to existing components without introducing breaking changes.

_TODO_

**Comment by pellared** [comment]
> All the metrics SDK methods SHOULD allow optional parameter(s) to be added to existing methods without introducing breaking changes, if possible.

_TODO_

**Comment by pellared** [comment]
It looks like we comply with this fragment of the specification.

@MrAlias Can you please double-check and close if you agree with my verification?

**Comment by pellared** [comment]
[`otlpmetricgrpc.New`](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc#New) and [`otlpmetrichttp.New`](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp#New) are components returned as interfaces. It would not possible to add a new methods that would control the exporter without creating a new method like NewBis that would return a struct (or other interface). I think it would be more flexible if both methods return structs instead of Exporter interface. The same is already done for span exporters.

**Comment by pellared** [comment]
Probably not a blocker but I think that `prometheus.Exporter` should not have the `Reader` field embedded (as it can be accessed and modified). I think it would be better to use "delegation" instead of embedding.

https://github.com/open-telemetry/opentelemetry-go/blob/55fb2bb57b47133d0b966e4d55151fba47aae057/exporters/prometheus/exporter.go#L53

**Comment by MadVikingGod** [comment]
Is there anything left to do on this issue?

**Comment by pellared** [comment]
Double-checked. Closing.
