### ISSUE TITLE
Confusing error messages with metric multierror type if wrapped is unset

### ISSUE THREAD

**Issue by pkwarren** [open-telemetry/opentelemetry-go#3698]
### Description

We're seeing some errors which I believe are coming from opentelemetry-go with the prefix `%!w(<nil>): `.

### Environment

- OS: Linux
- Architecture: x86_64
- Go Version: 1.19.5
- opentelemetry-go version: v0.35.0 (Metrics)

### Steps To Reproduce

1. Unknown how error is triggered (could be easily reproduced in a testcase however).

This appears to be the culprit:
* https://github.com/open-telemetry/opentelemetry-go/blob/d5fca833d6f6fc75e092c2108e0265aa778b8923/sdk/metric/pipeline.go#L507 creates a multierror with no wrapped error.
* https://github.com/open-telemetry/opentelemetry-go/blob/d5fca833d6f6fc75e092c2108e0265aa778b8923/sdk/metric/pipeline.go#L527 is called.

### Expected behavior

We shouldn't wrap errors if the error is nil. To fix, I think we should either:
1. Set `m.wrapped` if nil when calling `func (m *multierror) append(err error)`.
2. Special case in `errorOrNil()` to remove the prefix `%w: ` if wrapped is not set.

**Comment by ChillOrb** [comment]
@pkwarren 

Hey, this could be because wrapper is not initialized like [here](https://github.com/open-telemetry/opentelemetry-go/blob/2f3c6df7bbb674cfe32c93f62e1eb7d7f813511a/sdk/metric/pipeline.go#L217) 

i was looking into %w from the [go blog  ](https://go.dev/blog/go1.13-errors) and feel %w here is used incorrectly. Please correct me if i am wrong. 

> Wrapping errors with %w
> 
> As mentioned earlier, it is common to use the fmt.Errorf function to add additional information to an error.
> 
> if err != nil {
>     return fmt.Errorf("decompress %v: %v", name, err)
> }
> In Go 1.13, the fmt.Errorf function supports a new %w verb. When this verb is present, the error returned by fmt.Errorf will have an Unwrap method returning the argument of %w, which must be an error. In all other ways, %w is identical to %v.
> 
> if err != nil {
>     // Return an error which unwraps to err.
>     return fmt.Errorf("decompress %v: %w", name, err)
> }
> Wrapping an error with %w makes it available to errors.Is and errors.As:
> 
> err := fmt.Errorf("access denied: %w", ErrPermission)
> ...
> if errors.Is(err, ErrPermission) ...
> 

Summing up, 

- When you want to add additional context to an error without losing the original error information.
- When you want to chain multiple errors together to provide more detail about the error.
- When you want to wrap a specific error and modify the error message, but still have access to the original error information.

But here, we are using "errors  []string" to append errors if we encounter one .. According to me we should do either use a  slice or use %w.. 

If we were to implement this with %w we could do something like [go playground ](https://go.dev/play/p/YYUJ5jeRSZd)

Please let me know what you think...
