### ISSUE TITLE
Add debug logging to metric signal

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3722]
Similar to the trace signal we need to have a way for users to debug the system. Add logging to show flow of data.

**Comment by clesleycode** [comment]
What level of detail would you suggest? The first things that come to mind are:

1. Metric name
2. Timestamp 
3. Instrumentation library
4. Labels
5. Exporter type
6. Aggregation type

**Comment by MadVikingGod** [comment]
I would think that 1, 2, 3, and 4 would have us recreating the metrics in debug logs.

Instead, I would want to capture the configuration of the SDK, similar to what the Tracer does, and events related to SDK operations, like when a periodic reader fires information related to what was exported. Maybe a line when we first create an instrument.

The goal is not to capture every interaction with our library, because the instrumentor can print their own debug with more context than we would have, but to capture the internal workings that aren't exposed to the instrumentor/user.
