### ISSUE TITLE
metric identity and aggregation for duplicate instrument registration

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-go#3835]
### Description

https://github.com/open-telemetry/opentelemetry-specification/blob/ec84e5dcd77f36e79c0fe9bb1444d62be79dbb38/specification/metrics/sdk.md#duplicate-instrument-registration

>Based on [the recommendations from the data model](https://github.com/open-telemetry/opentelemetry-specification/blob/ec84e5dcd77f36e79c0fe9bb1444d62be79dbb38/specification/metrics/data-model.md#opentelemetry-protocol-data-model-producer-recommendations), the SDK MUST aggregate data from identical Instruments together in its export pipeline.

>The term identical applied to Instruments describes instances where all [identifying fields](https://github.com/open-telemetry/opentelemetry-specification/blob/ec84e5dcd77f36e79c0fe9bb1444d62be79dbb38/specification/metrics/api.md#instrument) are equal.

### Environment

- OS: [e.g. any]
- Architecture: [e.g. any]
- Go Version: [e.g. any]
- opentelemetry-go version: [e.g. v1.15.0-rc.1/v0.38.0-rc.1]

### Steps To Reproduce

1. Create multiple instruments with same name but different case such as `request_counter`, `request_Counter`, `Request_Counter`
2. Notice SDK doesn't aggregate the data for identical instruments 

### Expected behavior

2. Data must be aggregated for multiple instruments with same identity.

**Comment by MadVikingGod** [comment]
In the data model, there is nothing that makes any field case insensitive.  Those would be instruments with different names.

Is there something I am missing where these should be treated as the same instrument?

**Comment by MrAlias** [comment]
> In the data model, there is nothing that makes any field case insensitive. Those would be instruments with different names.
> 
> Is there something I am missing where these should be treated as the same instrument?

I think the issue here is the [API defines](https://github.com/open-telemetry/opentelemetry-specification/blob/a2a913a6dc72806749b2943ac64680cdc759dcde/specification/metrics/api.md#instrument-name-syntax) instrument names as case insensitive:

> They are case-insensitive, ASCII strings.

And the SDK ["MUST aggregate data from identical Instruments together in its export pipeline."](https://github.com/open-telemetry/opentelemetry-specification/blob/a2a913a6dc72806749b2943ac64680cdc759dcde/specification/metrics/sdk.md#duplicate-instrument-registration) Where, "[t]he term identical applied to Instruments describes instances where all identifying fields are equal." With instrument's `name`, `kind`, `unit`, `description`, and number type are all considered identifying.

It seems like this issue is identifying that given the Go SDK does not aggregate data from instruments with case-insensitive identical names together it is not compliant with the specification.

**Comment by MrAlias** [comment]
Reopening as https://github.com/open-telemetry/opentelemetry-specification/issues/3539 looks to be heading to a resolution other than what was done to resolve this.

Currently we emit two streams, and the specification looks to be heading to a consensus to emit just the first-value and log a warning.

**Comment by MrAlias** [comment]
Moved to being blocked by the specification issue:

- [ ] https://github.com/open-telemetry/opentelemetry-specification/issues/3539
