### ISSUE TITLE
Add `Warn` internal logging function

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#3866]
> Ended up not creating a `Warn` function as mentioned in the issue since Info is already being used for warning messages in other places.

_Originally from https://github.com/open-telemetry/opentelemetry-go/issues/3854_

We should consider adding `Warn` logging function to `go.opentelemetry.io/otel/internal/global`.

**Comment by unicod3** [comment]
I can work on this one but have a question, Is there any agreed verbosity level for the `Warn`?  

As far as I see we currently have `Debug (v-level: 5)` and `Info (v-level: 1)`,  Ideally verbosity level of  _warn_ should be lower than _info_ since it is meant to be more important than _info_. 

One approach could be changing the verbosity level of _info_ close to _debug_, but I am not sure about implications of it.

**Comment by MrAlias** [comment]
> I can work on this one but have a question, Is there any agreed verbosity level for the `Warn`?
> 
> As far as I see we currently have `Debug (v-level: 5)` and `Info (v-level: 1)`, Ideally verbosity level of _warn_ should be lower than _info_ since it is meant to be more important than _info_.
> 
> One approach could be changing the verbosity level of _info_ close to _debug_, but I am not sure about implications of it.

Can we map to a sudo inverse of what the OTel logging spec is: https://github.com/open-telemetry/opentelemetry-specification/blob/c10191c1bf2a6961145f3c5c1b16b89d54af02c0/specification/logs/data-model.md#field-severitynumber

**Comment by MadVikingGod** [comment]
The reason that the original values were chosen was to somewhat match expectations of current uses of logr.

Most uses of logr on github, only even use level 0. A few will use level 1 with a `-v` flag.  And there were one or two uses of 5 for debug-level logging.
