### ISSUE TITLE
Explore moving `readFile` to `host_id_bsd.go`

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3972]
Currently it is ignored as unused by the linter because it will fail on systems that do not built the resource detector that uses it.

The possibility of moving it should be explored.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-go/pull/3956#discussion_r1159379900_

**Comment by unicod3** [comment]
Hey @MrAlias, 

I've started looking into this, since linter complained about it I thought there might be a way to tell golangci-lint that it is used in other platforms but it seems there is no way to tell this as of now, see: https://github.com/dominikh/go-tools/issues/938

It seems `host_id_linux` also calls it. I'll check how we can move into the platform files.   

https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/resource/host_id_linux.go#L21
