### ISSUE TITLE
Add ExplicitBucketBoundaries hint API

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#4003]
### Problem Statement

The specification has added an [advice API](https://github.com/open-telemetry/opentelemetry-specification/blob/4ac43da9d746fea42523187685f341321a1d6ee1/specification/metrics/api.md#instrument-advice). The Go API doesn't currently support this feature.

### Proposed Solution

Add support for this feature.

#### Prior Art

[Java implementation](https://github.com/open-telemetry/opentelemetry-java/blob/8f6f9e712d55d45750b39adc4d964412cf88b190/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/descriptor/Advice.java).

**Comment by liufuyang** [comment]
Hey there, thanks for note down the issue here, any progress on this? Looks like it is called `advisory parameters` now?

And it would be nice if this stable `ExplicitBucketBoundaries` can be added soon and also having an example showing how to use it :)

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-advisory-parameter-explicitbucketboundaries

**Comment by pellared** [comment]
@dashpole, is it not solved via #4603 and #4605?

**Comment by dashpole** [comment]
Yes
