### ISSUE TITLE
Prometheus exporter should use stateful batcher

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#426]
While attempting to configure a Prometheus exporter I discovered that counter metrics were not behaving as expected, their values would fluctuate up and down and the metrics would disappear from the scrape endpoint when the system was not active.  I believe this is because [prometheus.NewExportPipeline()](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporter/metric/prometheus/prometheus.go#L153) missed the change to a stateful batcher from #385 when merge conflicts were resolved in #395.

**Comment by paivagustavo** [comment]
Thanks for reporting this right @Aneurysm9. You're right, the batcher should be stateful things must be messed with these merges :)

I've filled #428 to fix that. Once that is merged, could you check if this fixes the problem you're reporting? Otherwise we may need some more information to debug it.

**Comment by lizthegrey** [comment]
Addressed in [v0.2.1.1](https://github.com/open-telemetry/opentelemetry-go/releases/tag/v0.2.1.1)

**Comment by Aneurysm9** [comment]
@paivagustavo thanks for the quick fix. I can confirm that the exporter is now exhibiting the expected behavior.

**Comment by paivagustavo** [comment]
Happy that it was fixed, thank you for getting back!
