### ISSUE TITLE
Propagate traces across microservices

### ISSUE THREAD

**Issue by Kaushal28** [open-telemetry/opentelemetry-go#4302]
I have two Go based micro services: client and server. I want my traces that I create in client should also include the spans created in the server. Currently I have implemented manual tracing in both the services, but I am not sure how to link them. Currently, Is it possible in Go?

In the official docs (https://opentelemetry.io/docs/instrumentation/go/manual/#propagators-and-context) I couldn't find any example. As mentioned in above doc, how to use auto instrumentation in Go to achieve this?

**Comment by dmathieu** [comment]
That's because the only required example is in that demo.
When you define a propagator, it's expected to be used by the library which handles communication across the services.

For example, if you communicate through HTTP, the `net/http` instrumentation library [extracts](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/handler.go#L136) the current context into HTTP headers for outgoing requests.
And the incoming handler [injects](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/transport.go#L114) the passed data into the context.

You can dig deeper to see how it all works (with a bit of [self promotion from me](https://dmathieu.com/articles/development/opentelemetry-propagation/) for example), but if you only want to get it to work, that's all you need.
