### ISSUE TITLE
prometheus exporter: resource attribute labels

### ISSUE THREAD

**Issue by trajan0x** [open-telemetry/opentelemetry-go#4392]
### Problem Statement

Let's say I'm creating a number of meters in an exporter that scrapes several different sources. To distinguish these/for ease of access in grafana I'd like to have labels attached to each metric, like [this](https://github.com/synapsecns/sanguine/blob/3bbd54eeaf9e2baf9909787e7c96092bca1b26bd/contrib/promexporter/exporters/exporter.go#L147)

The problem is these are not exported. As a matter of fact, I couldn't find a single use of this attribute outside of a test.

### Proposed Solution

I'm not really sure if the expected behavior here is to pass this down to meters created (the way you would w/ metric.WithAttributes in o.Observe) or something else, but how to add labels was vey unclear to me until I searched and found [this file](https://github.com/Arthur1/otlc/blob/27866d6f826d6aa267f1f0de1687fddfe50b89b9/metrics/post.go#L68)

I'd also like to suggest moving the metric.WithAttributes section to the gauge creation step. I think that's much less ambiguous

### Additional Context

Feel free to close this issue if it is unclear/malformed

**Comment by dashpole** [comment]
Those attributes should be attached as labels on the otel_scope_info metric.  Since all metrics have the scope name and version, you can join (`group_left` in promql) the otel_scope_info metric with any of the metrics you define in your meter to add the additional attributes.

> I'd also like to suggest moving the metric.WithAttributes section to the gauge creation step. I think that's much less ambiguous

Just to be perfectly clear, you can add attributes when making observations.  E.g. 
```golang
o.ObserveFloat64(balanceGauge, truncEthBalance, metric.WithAttributes(
	attribute.Key("A").String("B"),
	attribute.Key("C").String("D"),
))
```

Generally speaking, WithInstrumentationAttributes shouldn't be used except for attributes that describe the library.  If you want the attributes to appear on all of your metrics, you probably want to use metric.WithAttributes as shown above.

**Comment by dmathieu** [comment]
@trajan0x did @dashpole's comment answer your question? Can this issue be closed?

**Comment by trajan0x** [comment]
Yep
