### ISSUE TITLE
trace.TraceContext stutters

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/opentelemetry-go#448]
Currently golint warning on [trace.TraceContext ](https://github.com/open-telemetry/opentelemetry-go/blob/6b4acf47b8cd3b106cc29d3ad6cad764ebf880fb/api/trace/trace_context_propagator.go#L39-L40) is disabled. Opened this issue to find a better name.

**Comment by krnowak** [comment]
Thanks for filing this issue for me.

To expand on it a bit: `TraceContext` used to be in `propagators` package, so there was no stutter, and it was clear that it was a propagator because of the package name. Now it has been moved to the `trace` package, so it stutters and the `trace.TraceContext` name does not make it clear that it is a propagator. The `trace.B3` propagator is also affected - not clear that it is a propagator.

Also, we are going to have the same problem later when we split the correlation context propagation from `trace.TraceContext` into the `correlation` package - we will get something like `correlation.CorrelationContext` or something.

So to solve the issue, I'm proposing the following:

- Append the `Propagator` to the type name (so we will have `trace.TraceContextPropagator`, `trace.B3Propagator` and, in future, `correlation.CorrelationContextPropagator`. Now it's clear that those types are propagators.
- Since `trace.TraceContextPropagator` and `correlation.CorrelationContextPropagator` are awfully long and they stutter, we need to shorten/fix their names. Since both of them are implementations of some W3C spec, we could name them `trace.W3CPropagator` and `correlation.W3CPropagator`, respectively.

@rghetia also proposed naming `trace.TraceContext` as `trace.ContextPropagator` which, to me, sounds too generic, because `trace.B3Propagator` is also a context propagator.

**Comment by rghetia** [comment]
> * Since `trace.TraceContextPropagator` and `correlation.CorrelationContextPropagator` are awfully long and they stutter, we need to shorten/fix their names. Since both of them are implementations of some W3C spec, we could name them `trace.W3CPropagator` and `correlation.W3CPropagator`, respectively.

I like W3CPropagator.

**Comment by iredelmeier** [comment]
I'm personally wary of `W3C` as it feels somewhat un-obvious and is meant to be _the_ standard. You wouldn't say `W3CContentLength`.

**Comment by rghetia** [comment]
@iredelmeier do you any suggestion if not W3CPropagator?

**Comment by MikeGoldsmith** [comment]
I like the addition of adding Propagator as a suffix tot he types to help people understand the intent.

If W3C is the meant to be the default/standard, could we name it `DefaultPropagator`? I'm not a huge fan of this incase we wish to change the default to something else in the future.

**Comment by krnowak** [comment]
> If W3C is the meant to be the default/standard, could we name it `DefaultPropagator`? I'm not a huge fan of this incase we wish to change the default to something else in the future.

DefaultPropagator is something else - we have this as a function for both span context and correlation context that returns a propagator.

**Comment by MrAlias** [comment]
> we could name them trace.W3CPropagator and correlation.W3CPropagator, respectively

I'll throw my support behind this. I think the fully-qualified name (i.e. including the `trace.` and `correlation.` prefix) make the intent clear. To me it indicates the trace or correlation propagator defined by the W3C.

However, if including the standards body as part of the name is ultimately not desired, could we just use `trace.Propagator` and `correlation.Propagator`? [The specification states these are the format to support](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-propagators.md#global-propagators):

> Implementations MAY provide global Propagators for each supported Format.
>
> If offered, the global Propagators should default to a composite Propagator containing W3C Trace Context and Correlation Context Propagators, in order to provide propagation even in the presence of no-op OpenTelemetry implementations.

Seems like just calling them `*Propagator`, while losing implementation details, is in line with the project.

**Comment by jmacd** [comment]
I think I would be OK with `trace.Context`.

**Comment by MrAlias** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-go/pull/1118
