### ISSUE TITLE
Verify metric OTLP exporters compliance with the configuration specification

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#4512]
Specification: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/protocol/exporter.md

Create an issue for anything not compliant.

**Comment by MadVikingGod** [comment]
I took this to mean the Configuration Option section of the specification, and the rest in the other ticket #4511.

## [Configuration Options](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/protocol/exporter.md#configuration-options)

The following configuration options **MUST** be available to configure the OTLP exporter. 
Each configuration option **MUST** be overridable by a signal specific option.

- [ ] Endpoint (OTLP/HTTP): 
    - [ ] The endpoint MUST be a valid URL with scheme (http or https) and host, 
    - [ ] The endpoint MAY contain a port, 
    - [ ] The endpoint SHOULD contain a path 
    - [ ] The endpoint MUST NOT contain other parts (such as query string or fragment). 
    - [ ] When using OTEL_EXPORTER_OTLP_ENDPOINT, 
        - [ ] exporters MUST construct per-signal URLs as described below. 
        - [ ] *Not Normative here, but is by other parts of the spec* The per-signal endpoint configuration options take precedence and can be used to override this behavior (the URL is used as-is for them, without any modifications). 
    - [ ] *Not Normative* Default: http://localhost:4318 
        - [ ] SDKs SHOULD default endpoint variables to use http scheme unless they have good reasons to choose https scheme for the default (e.g., for backward compatibility reasons in a stable SDK release).
    - [ ] Env vars: 
        - [ ] OTEL_EXPORTER_OTLP_ENDPOINT 
        - [ ] OTEL_EXPORTER_OTLP_METRICS_ENDPOINT 
        
- [ ] Endpoint (OTLP/gRPC): 
    - [ ] The endpoint SHOULD accept any form allowed by the underlying gRPC client implementation.
    - [ ] The endpoint MUST accept a URL with a scheme of either http or https.
    - [ ] If the gRPC client implementation does not support an endpoint with a scheme of http or https then the endpoint SHOULD be transformed to the most sensible format for that implementation.
    - [ ] *Not Normative* Default: http://localhost:4317 
        - [ ] SDKs SHOULD default endpoint variables to use http scheme unless they have good reasons to choose https scheme for the default (e.g., for backward compatibility reasons in a stable SDK release).
    - [ ] Env vars:
        - [ ] OTEL_EXPORTER_OTLP_ENDPOINT 
        - [ ] OTEL_EXPORTER_OTLP_METRICS_ENDPOINT 
        
- [ ] Insecure: 
    - [ ] *Not Normative* This option only applies to OTLP/gRPC when an endpoint is provided without the http or https scheme - [ ] OTLP/HTTP always uses the scheme provided for the endpoint. 
    - [ ] Implementations MAY choose to not implement the insecure option if it is not required or supported by the underlying gRPC client implementation.
    - [ ] *Not Normative* Default: false
    - [ ] Env vars: 
        - [ ] OTEL_EXPORTER_OTLP_INSECURE 
        - [ ] OTEL_EXPORTER_OTLP_METRICS_INSECURE 
        - [ ] OTEL_EXPORTER_OTLP_METRIC_INSECURE

- [ ] Certificate File: 
    - [ ] *Not Normative* Default: n/a
    - [ ] Env vars: 
        - [ ] OTEL_EXPORTER_OTLP_CERTIFICATE
        - [ ] OTEL_EXPORTER_OTLP_METRICS_CERTIFICATE
        
- [ ] Client key file:
    - [ ] *Not Normative* Default: n/a
    - [ ] Env vars: 
        - [ ] OTEL_EXPORTER_OTLP_CLIENT_KEY 
        - [ ] OTEL_EXPORTER_OTLP_METRICS_CLIENT_KEY

- [ ] Client certificate file: 
    - [ ] *Not Normative* Default: n/a
    - [ ] Env vars: 
        - [ ] OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE
        - [ ] OTEL_EXPORTER_OTLP_METRICS_CLIENT_CERTIFICATE 
        
- [ ] Headers:
    - [ ] *Not Normative* Default: n/a
    - [ ] Env vars: 
        - [ ] OTEL_EXPORTER_OTLP_HEADERS 
        - [ ] OTEL_EXPORTER_OTLP_METRICS_HEADERS 
        
- [ ] Compression: 
    - [ ] *Not Normative* Supported compression: gzip, none.
    - [ ] *Not Normative* Default: No value [2]
    - [ ] *Not Normative* If no compression value is explicitly specified, SIGs can default to the value they deem most useful among the supported options
    - [ ] Env vars: 
        - [ ] OTEL_EXPORTER_OTLP_COMPRESSION 
        - [ ] OTEL_EXPORTER_OTLP_METRICS_COMPRESSION 
        
- [ ] Timeout: 
    - [ ] *Not Normative* Default: 10s
    - [ ] Env vars: 
        - [ ] OTEL_EXPORTER_OTLP_TIMEOUT 
        - [ ] OTEL_EXPORTER_OTLP_METRICS_TIMEOUT 
    
- [ ] Protocol: 
    - [ ] Options MUST be one of: grpc, http/protobuf, http/json.
    - [ ] *Not Normative* Default: http/protobuf [3]
    - [ ] Env vars: 
        - [ ] OTEL_EXPORTER_OTLP_PROTOCOL 
        - [ ] OTEL_EXPORTER_OTLP_METRICS_PROTOCOL

**Comment by MadVikingGod** [comment]
# [Endpoint URLs for OTLP/HTTP](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/protocol/exporter.md#endpoint-urls-for-otlphttp)

- [ ] Based on the environment variables above, the OTLP/HTTP exporter MUST construct URLs for each signal as follow:

    - [ ] For the per-signal variables (OTEL_EXPORTER_OTLP_<signal>_ENDPOINT), the URL MUST be used as-is without any modification. 
    - [ ] If an URL contains no path part, the root path / MUST be used.
    - [ ] If OTEL_EXPORTER_OTLP_ENDPOINT is used path should be `v1/metrics``.

- [ ] An SDK MUST NOT modify the URL in ways other than specified above. 
- [ ] If the port is empty or not given, 
    - [ ] TCP port 80 is the default for the http scheme 
    - [ ] TCP port 443 is the default for the https scheme

# [Specify Protocol](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/protocol/exporter.md#specify-protocol)

- [ ] SDKs SHOULD support both grpc and http/protobuf transports
- [ ] SDKs MUST support one of grpc and http/protobuf transports
- [ ] If they support only one, it SHOULD be http/protobuf.
- [ ] SDKs MAY support http/json.
- [ ] If no configuration is provided the default transport SHOULD be http/protobuf

# [Specifying headers via environment variables](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/protocol/exporter.md#specifying-headers-via-environment-variables)

- [ ] All attribute values MUST be considered strings.


# [Retry](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/protocol/exporter.md#retry)

- [ ] Transient errors MUST be handled with a retry strategy. 
- [ ] The retry strategy MUST implement an exponential back-off with jitter.

## [Transient errors](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/protocol/exporter.md#transient-errors)

- [ ] Transient errors are defined by the [OTLP protocol specification](https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md#failures).

For OTLP/gRPC, transient errors are defined by a set of retryable gRPC status codes.
For OTLP/HTTP, transient errors are defined by:
    A set of retryable HTTP status codes received from the server.
    The scenarios described in: All other responses and OTLP/HTTP Connection.

# [User Agent](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/protocol/exporter.md#user-agent)

- [ ] OpenTelemetry protocol exporters SHOULD emit a User-Agent header to at a minimum identify the exporter, the language of its implementation, and the version of the exporter. 
- [ ] The format of the header SHOULD follow RFC 7231.

**Comment by pellared** [comment]
From https://github.com/open-telemetry/opentelemetry-specification/blob/v1.26.0/specification/protocol/exporter.md#specify-protocol:

> The `OTEL_EXPORTER_OTLP_PROTOCOL`, `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL`, and `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL` environment variables specify the OTLP transport protocol

The specification does NOT seem to require to support these environmental values (it does not any normative language and it does not say anywhere that it has to be supported). So we are compliant.

However, I started to think that it might be more useful for the users if we have a single `otlpmetric` Go module and package instead of `otlpmetrichttp` and `otlpmetricgrpc`. Take notice that both Go modules have the exact same dependencies ([`go.mod` of otlpmetrichttp](https://github.com/open-telemetry/opentelemetry-go/blob/f14dc1281d10939b8ceaf8ccf5eea9a324732ae2/exporters/otlp/otlpmetric/otlpmetrichttp/go.mod) and [`go.mod` of otlpmetricgrpc](https://github.com/open-telemetry/opentelemetry-go/blob/f14dc1281d10939b8ceaf8ccf5eea9a324732ae2/exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod)). Thanks to it we would be able to add support for `OTEL_EXPORTER_OTLP_PROTOCOL` and `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL`. To do it we would probly would need to add `WithGRPCProtocol` and `WithHTTPProtocol` options, define `GRPCProtocolOptions` and ``HTTPProtocolOptions` and refactor some existing options to them.

The main drawback of merging  `otlpmetrichttp` and `otlpmetricgrpc` would be the fact that this would be a breaking change for our existing users. The alternative approach could be to provide support for `OTEL_EXPORTER_OTLP_PROTOCOL` and `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL` via https://pkg.go.dev/go.opentelemetry.io/contrib/exporters/autoexport. However, https://pkg.go.dev/go.opentelemetry.io/contrib/exporters/autoexport does not allow fine-grained OTLP exporter setup.

The other drawback is that the OTLP trace exporters and OTLP metric exporters would have different API/design which may look very strange. I find "self-similarity" an important aspect of API design.

Personally, because of the two drawbacks I listed above,  I think that it would be probably better to leave the current `otlpmetrichttp` and `otlpmetricgrpc` split.

**Comment by pellared** [comment]
Blocked by:

- https://github.com/open-telemetry/opentelemetry-specification/issues/3717
