### ISSUE TITLE
Verify OpenCensus bridge is compatible with the specificaiton

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#4514]
Specification: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/compatibility/opencensus.md

Create an issue for anything not compliant.

**Comment by dashpole** [comment]
> The trace bridge is provided as a shim layer implementing the [OpenCensus Trace API](https://github.com/census-instrumentation/opencensus-specs) using the OpenTelemetry Trace API. This layer MUST NOT rely on implementation specific details of the OpenTelemetry SDK.

It does not depend on the trace SDK: https://github.com/open-telemetry/opentelemetry-go/blob/60666c554065ac4da502fe28943eea4b938ab479/bridge/opencensus/go.mod#L5-L12

> This Shim Layer MUST NOT publicly expose any upstream OpenTelemetry API.

The bridge will accept a TracerProvider, but does not expose any OpenTelemetry API interfaces in its public API.

> Easy for users to use, ideally no change to their code

The InstallTraceBridge() function (added in https://github.com/open-telemetry/opentelemetry-go/pull/4567) is as simple as we could possibly get.

> Maintain parent-child span relationship between applications and libraries

The bridge does this, as tested here: https://github.com/open-telemetry/opentelemetry-go/blob/main/bridge/opencensus/test/bridge_test.go#L32

> This component MUST be an optional dependency.

The bridge is in its own module, and thus is fully optional.

> When the shim is in place, all OpenCensus Spans MUST be sent through an OpenTelemetry Tracer as specified for the OpenTelemetry API.

The current API, NewTracer, accepts an OpenTelemetry Tracer, which it uses to record spans from OpenCensus: https://github.com/open-telemetry/opentelemetry-go/blob/60666c554065ac4da502fe28943eea4b938ab479/bridge/opencensus/trace.go#L29

After https://github.com/open-telemetry/opentelemetry-go/pull/4567, this will still be the case in InstallTraceBridge: https://github.com/open-telemetry/opentelemetry-go/pull/4567/files#diff-ee40e63756bf77fde5a66bcf047e3bee7ae65207d633d2a4dc9139a8b7d6362fR40

> This mechanism SHOULD be seamless to the user in languages that allow discovery and auto injection of dependencies.

I don't believe this applies to Go.

> All specified methods in OpenCensus will delegate to the underlying Span of OpenTelemetry.

The bridge span wrapper delegates all OpenCensus calls to the OpenTelemetry tracer: https://github.com/open-telemetry/opentelemetry-go/blob/60666c554065ac4da502fe28943eea4b938ab479/bridge/opencensus/internal/span.go#L43-L45

**The OpenCensus Trace Bridge is compliant with the specification.**

**Comment by dashpole** [comment]
### Metrics Bridge

> OpenTelemetry will provide an OpenCensus-Metrics-Shim component which implements the OpenTelemetry [MetricProducer](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/metrics/sdk.md#metricproducer) interface.

opencensus.NewMetricProducer returns a metric.Producer: https://github.com/open-telemetry/opentelemetry-go/blob/main/bridge/opencensus/metric.go#L37

> When Produce() is invoked, the shim collects metrics from the OpenCensus global state, converts the metrics to an OpenTelemetry metrics batch, and returns.

https://github.com/open-telemetry/opentelemetry-go/blob/60666c554065ac4da502fe28943eea4b938ab479/bridge/opencensus/metric.go#L44-L58

> This component MUST be an optional dependency

The bridge is in its own go module, which makes it optional for users to use.

> MUST NOT require OpenTelemetry to be included in OpenCensus API distributions. SHOULD NOT require OpenCensus to depend on OpenTelemetry at runtime


OpenCensus does not depend on OpenTelemetry

> MUST require few or no changes to OpenCensus

No changes were required to OpenCensus for this bridge.

> MUST be compatible with push and pull exporters

ManualReader, PeriodicReader, and the prometheus exporter all accept metric.Producer as a source of external metrics.

> MUST support Gauges, Counters, Cumulative Histograms, and Summaries

**We do not support summaries today.**  https://github.com/open-telemetry/opentelemetry-go/issues/4571

Gauges, Counters, Cumulative Histograms: https://github.com/open-telemetry/opentelemetry-go/blob/60666c554065ac4da502fe28943eea4b938ab479/bridge/opencensus/internal/ocmetric/metric.go#L69-L78

> MUST support exemplar span context in language that provide utilities for recording span context in exemplars

**We do not support exemplars today**: https://github.com/open-telemetry/opentelemetry-go/issues/4572

> The shim MUST discard the resource attached to OpenCensus metrics, and insert the resource provided during initialization, or fall back to the the default OpenTelemetry resource.

We discard the resource attached to OpenCensus, since the bridge does not return a resource.  The OTel metrics SDK inserts the resource provided during initialization, or falls back to the default.

> The shim MUST add an instrumentation scope name and version which identifies the shim.

We do add a scope with a name, but **do not add a version**: https://github.com/open-telemetry/opentelemetry-go/issues/4573

> The shim can be passed as an option to an OpenTelemetry [MetricReader](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/metrics/sdk.md#metricreader) when configuring the OpenTelemetry SDK. This enables the bridge to work with both push and pull metric exporters.

The OpenCensus bridge can be passed to PeriodicReader, ManualReader, and the Prometheus exporter.

**Comment by dashpole** [comment]
Remaining compliance issues:

* https://github.com/open-telemetry/opentelemetry-go/issues/4571
* https://github.com/open-telemetry/opentelemetry-go/issues/4572
* https://github.com/open-telemetry/opentelemetry-go/issues/4573

**Comment by dashpole** [comment]
Based on the above, I think the bridge is compatible with the specification.  If someone else can review my analysis above, I think we can close.

**Comment by pellared** [comment]
I am not sure if we want the "Trace Bridge" and "OpenCensus-Metrics-Shim" should be contained in a single Go module.
The components have different dependencies (mainly OTel Trace API vs OTel Metrics SDK).

Maybe we should provide `opencensustrace` (or `octrace`)  and (or `ocmetric`) Go modules in subdirectories? I am leaning towards `oc*` naming as `opensensus` will be already in the import path.
