### ISSUE TITLE
Implement Context propagation

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/opentelemetry-go#477]
Implement Context propagation as per the spec.

**Comment by krnowak** [comment]
This is copy of a post from #457 about suppliers:

So this issue conflicts with the following issues in the otel-spec (as we will likely need to rework the supplier interface for allowing multi-valued keys and rework propagator interface to have an iterator over keys instead of a function for getting a fixed list of the keys the propagator uses/understands):

https://github.com/open-telemetry/opentelemetry-specification/issues/433
https://github.com/open-telemetry/opentelemetry-specification/issues/443
https://github.com/open-telemetry/opentelemetry-specification/issues/444

**Comment by krnowak** [comment]
This is done. The supplier interface is still in works on the specification side.
