### ISSUE TITLE
auto instrumentation not working in eks 1.27

### ISSUE THREAD

**Issue by shishir84** [open-telemetry/opentelemetry-go#4814]
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: auto-instrumentation
  namespace: wingspan
spec:
  exporter:
    endpoint: "http://observability-collector.aws-otel-eks.svc.cluster.local:4317"
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  java:
    image: repo/autoinstrumentation-java:1.0.0
  nodejs:
    image: repo/autoinstrumentation-nodejs:1.0.0
  python:
    image: repo//autoinstrumentation-python:1.0.0

after creating this getting 

error: no kind "Instrumentation" is registered for version "opentelemetry.io/v1alpha1" in scheme "pkg/scheme/scheme.go:28"

opentelemetry-operator:
kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml

**Comment by scorpionknifes** [comment]
Hey @shishir84, thanks for reporting an issue, I think this issue is belongs to [open-telemetry/opentelemetry-operator](https://github.com/open-telemetry/opentelemetry-operator) instead. [open-telemetry/opentelemetry-go](https://github.com/open-telemetry/opentelemetry-go) is for the Go language Go API and SDK for OpenTelemetry. For further help, I do recommend checking out the slack channels available here: https://opentelemetry.io/community/ thanks

**Comment by dmathieu** [comment]
I agree with @scorpionknifes here. This issue should be either in opentelemetry-operator, or in [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector).
