### ISSUE TITLE
Add histogram support for prometheus exporter

### ISSUE THREAD

**Issue by paivagustavo** [open-telemetry/opentelemetry-go#487]
Since #385 the ability to use histograms was removed until #317 was done. #317 is now merged to master and we can offer users of the prometheus exporter to use histograms instead of summaries.

Even further, histogram are usually more common and recommended when using prometheus and it should be the default aggregator for measures until we have a more fine grained config mechanism.

What need to be done:
1. Create a new selector on `go.opentelemetry.io/otel/sdk/metric/selector/simple` that returns a histogram aggregator for `MeasureKind`.
2.  Handle histogram aggregator on the prometheus [Collect method](https://github.com/open-telemetry/opentelemetry-go/blob/f99337fb8a1008c85d2ee0536900688276198b73/exporter/metric/prometheus/prometheus.go#L204)
2. Add config for custom histogram buckets, just like the `DefaultSummaryQuantiles` option on the exporter.
3. Change the [default selector](https://github.com/open-telemetry/opentelemetry-go/blob/f99337fb8a1008c85d2ee0536900688276198b73/exporter/metric/prometheus/prometheus.go#L139) for the prometheus exporter.

I'm happy to help if anyone want to take this, you can reach here or in gitter!

**Comment by wingyplus** [comment]
I would like to take this one.

**Comment by paivagustavo** [comment]
Hey @wingyplus, have you had time to take some time to this? If you need any help don't hesitate to get in touch :)

**Comment by alexandre-normand** [comment]
I'm going to drop this [branch here](https://github.com/open-telemetry/opentelemetry-go/compare/master...alexandre-normand:add-partial-support-for-histograms-in-prometheus-exporter?expand=1) here in case that would be helpful to anyone who would be looking to work on this. 

I stopped working on it when realizing that my use case would be better served by summaries rather than histograms. If anyone wants to grab it and carry this forward, I think that the next steps would be:
* Add missing `godoc`
* Add tests for histogram exporting in `prometheus_test.go`
* Potential clean up (this was my first time digging into this code so I wasn't fully confident)

**Comment by wingyplus** [comment]
Sorry for didn't replied for a long time. I'll have time slot to looking into it in this weekend. :D 

@alexandre-normand Thanks for your suggestion.
