### ISSUE TITLE
Allow to configure sampling strategy per SpanExporter

### ISSUE THREAD

**Issue by StarpTech** [open-telemetry/opentelemetry-go#5199]
### Problem Statement

Hi, we want to configure multiple `sdktrace.SpanExporter` but with a different sampling rate. Right now, this can only be achieved by creating multiple TraceProvider which is cumbersome to deal with.

### Proposed Solution

It should be possible to configure a sampling strategy per exporter.

#### Alternatives

Create multiple TraceProviders.

**Comment by dmathieu** [comment]
The samplers makes its decision at span creation (that's head sampling). If the sampler decides a span shouldn't be recorded, you will be getting a noop. So making sampling decisions per exporter at that level is not possible (it would require a V2, and specification changes).

What you want is tail sampling (sampling decision made when the span is closed/exported), which is not something officially supported on any SDK.
However, that should be relatively easy to do with a custom exporter (which can call a child exporter to perform the actual job).

Implement a [SpanExporter](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/trace#SpanExporter) which, does something like:

```golang
func (e *exporter) ExportSpans(ctx context.Context, spans []ReadOnlySpan) error {
    eSpans := []ReadOnlySpan{}
    for _, s := range spans {
        if e.sampler.ShouldSample(trace.SamplingParameters{ParentContext: s.Parent(), TraceID: s.TraceID, ...}) {
            eSpans = append(eSpans, s)
        }
    }

    return e.parent.ExportSpans(ctx, eSpans)
}
```

Then, each exporter can use that tail sampling exporter, and make its own decisions (and because you use the [Sampler](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/trace#Sampler) interface, you can reuse all the samplers provided).

**Comment by StarpTech** [comment]
Hi @dmathieu, thank you for the example. Tail sampling will make the deployment of the otelcollector significant more complex and cause much more traffic. The https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor is also not stable. The options here are very thin. I think the use case to sent data to multiple system with different configuration would be a great feature to add to the specification.

**Comment by dmathieu** [comment]
The tail sampling I'm talking about here is process-tail, it does not include the collector at all.

**Comment by StarpTech** [comment]
Got it. You want me to manipulate the final export of the exporter by reevaluating the sampling decision. I think this can work.

**Comment by dmathieu** [comment]
It will not be reevaluating the sampling decision.
You will never see non-sampled spans (from head sampling) in your exporters, so you can't "reevaluate" them. This is a second evaluation.

**Comment by StarpTech** [comment]
Ok.
