### ISSUE TITLE
Prometheus should support pushgateway

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/opentelemetry-go#522]
https://godoc.org/github.com/prometheus/client_golang/prometheus/push#Pusher.Push
https://prometheus.io/docs/practices/pushing/

**Comment by jmacd** [comment]
There are some drawbacks to the push gateway (e.g., "The Pushgateway never forgets series pushed to it and will expose them to Prometheus forever unless those series are manually deleted via the Pushgateway's API."), but I agree we should consider adding this support if it's not difficult.

I would hope that users are better off sending over OTLP and then exporting Prometheus from the otel-collector.

**Comment by kcq** [comment]
@jmacd are you suggesting to remove the Prometheus exporter functionality from the client library and rely on the collector to export to Prometheus?

**Comment by MrAlias** [comment]
We created the [experimental cortex exporter](https://pkg.go.dev/go.opentelemetry.io/contrib/exporters/metric/cortex) to support this, but have ultimately decided to not support this. Instead we recommend to use the OTLP to send data to the collector and use their [PRW exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusremotewriteexporter).

I'm closing this for now because we do not plan to address this addition for the foreseeable future.
