### ISSUE TITLE
Last-value-wins for Observer results

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#564]
The specification says that the last-value observed for a `LabelSet` wins.

I had tried to specify this here:
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-metrics.md#time

I am trying to strengthen this statement here:
https://github.com/open-telemetry/oteps/pull/88/files#diff-1fcf43b7ca9433b41b2223a40826906dR57

There is a TODO here about it:
https://github.com/open-telemetry/opentelemetry-go/pull/560/files#diff-c1a360562696dc33ee82c33529581877R309

**Comment by evantorrie** [comment]
I've read the current spec on [aggregations](https://github.com/open-telemetry/opentelemetry-specification/blob/4ab7c2fb4964c14fe972b03b5bb6825573bafb24/specification/api-metrics.md#aggregations) and [OTEP 88](https://github.com/open-telemetry/oteps/pull/88/files#diff-1fcf43b7ca9433b41b2223a40826906dR53), and am still a little confused.

The current spec says the SDK default aggregator for Observers should be `LastValue`, but the current implementation assigns them the same aggregator as `Measure` instruments, which is minimally `MinMaxSumCount`, rather than the available [`LastValue`](https://github.com/open-telemetry/opentelemetry-go/blob/a1c243965e9985555a40f3df50475b8e078fb1e0/sdk/metric/aggregator/lastvalue/lastvalue.go).

Is this issue relating only to cases where the aggregator for an Observable is **not** `LastValue`?

**Comment by jmacd** [comment]
I mistakenly filed this issue without emphasizing that the current specification will be replaced with the much-more-specified (hopefully) behavior described in OTEP 88, [here](https://github.com/open-telemetry/oteps/pull/88/files?short_path=1fcf43b#diff-1fcf43b7ca9433b41b2223a40826906d), where we refer to a "Last value relationship" instead of a "Last value" aggregation by default. IOW I got ahead of myself.

There is still a "Last value" aggregation that is well-defined, and most resembles the classic "Gauge" instrument--it is a synchronous instrument. In the OTEP 88 terminology, we might discuss standardizing a refinement of Measure with a default last-value relationship. 

OTOH, Observe instruments naturally define a last-value relationship. Generally, with observers, there is some other aggregation that is being applied. The point of this ticket here is that Observer instruments are **not allowed to observe more than one value per interval / label-set**.

**Comment by jmacd** [comment]
@krnowak this is a discussion related to your remarks in https://github.com/open-telemetry/opentelemetry-go/pull/560

We should wait until OTEP 88 is merged into the specification before moving forward on this. There is a question of how to actually implement the behavior too. The easy solution involves a new map. I am guessing it will be less overhead to sort and de-duplicate, re-using a temporary array for this purpose. (The same is done for labels within label sets here: https://github.com/open-telemetry/opentelemetry-go/blob/master/sdk/metric/sdk.go#L351)

To solve this,
