### ISSUE TITLE
Audit Compliance: Logs Bridge No-Op Implementation

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#5690]
1. Review the [Logs Bridge API No-Op Implementation specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.35.0/specification/logs/noop.md) for all normative statements
1. Audit the [logs bridge noop package](https://pkg.go.dev/go.opentelemetry.io/otel/log/noop) for compliance with the specified normative statements.
1. Identify existing issues or create new issues to track any work needed to make the [logs bridge noop package](https://pkg.go.dev/go.opentelemetry.io/otel/log/noop) compliant with the specification.

**Comment by XSAM** [comment]
Normative statements:
- It implements the [OpenTelemetry Logs Bridge API](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.35.0/specification/logs/bridge-api.md) so that no telemetry is produced and computation resources are minimized.
- All No-Op components
  - MUST NOT hold configuration or operational state.
  - All No-op operations MUST accept all defined parameters
  - MUST NOT validate any arguments received
  - MUST NOT return any non-empty error or log any message.

## LoggerProvider

- The No-Op MUST allow the creation of multiple LoggerProviders.
- A No-Op MAY provide the same LoggerProvider instances to all creation requests.
- LoggerProvider MUST allow for the creation of Loggers. All Loggers created MUST be an instance of the [No-Op Logger](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.35.0/specification/logs/noop.md#logger).

## Logger

The No-Op Logger MUST allow for [emitting LogRecords](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.35.0/specification/logs/bridge-api.md#emit-a-logrecord).

**Comment by XSAM** [comment]
## LoggerProvider

> - It implements the [OpenTelemetry Logs Bridge API](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.35.0/specification/logs/bridge-api.md) so that no telemetry is produced and computation resources are minimized.
> - All No-Op components
>   - MUST NOT hold configuration or operational state.
>   - All No-op operations MUST accept all defined parameters
>   - MUST NOT validate any arguments received
>   - MUST NOT return any non-empty error or log any message.
> 
> - The No-Op MUST allow the creation of multiple LoggerProviders.
> - A No-Op MAY provide the same LoggerProvider instances to all creation requests.
> - LoggerProvider MUST allow for the creation of Loggers. All Loggers created MUST be an instance of the [No-Op Logger](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.35.0/specification/logs/noop.md#logger).

https://github.com/open-telemetry/opentelemetry-go/blob/84677a6554fb9fee9359a10179c3a93a7bd6db89/log/noop/noop.go#L26

https://github.com/open-telemetry/opentelemetry-go/blob/84677a6554fb9fee9359a10179c3a93a7bd6db89/log/noop/noop.go#L30-L41

We are compliant.

**Comment by XSAM** [comment]
## Logger

> - It implements the [OpenTelemetry Logs Bridge API](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.35.0/specification/logs/bridge-api.md) so that no telemetry is produced and computation resources are minimized.
> - All No-Op components
>   - MUST NOT hold configuration or operational state.
>   - All No-op operations MUST accept all defined parameters
>   - MUST NOT validate any arguments received
>   - MUST NOT return any non-empty error or log any message.
> 
> - The No-Op Logger MUST allow for emitting LogRecords.

https://github.com/open-telemetry/opentelemetry-go/blob/84677a6554fb9fee9359a10179c3a93a7bd6db89/log/noop/noop.go#L27

https://github.com/open-telemetry/opentelemetry-go/blob/84677a6554fb9fee9359a10179c3a93a7bd6db89/log/noop/noop.go#L43-L50

We are compliant.

**Comment by XSAM** [comment]
@open-telemetry/go-maintainers I believe we comply with this part of the specification. Feel free to double-check and close this issue.
