### ISSUE TITLE
OTLP Log  gRPC ignores OTEL_EXPORTER_OTLP_INSECURE=true

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-go#5719]
Context:
https://github.com/open-telemetry/opentelemetry-go/blob/2db4ef2c032cd2390d18d01feeb37b71a7ca9469/exporters/otlp/otlplog/otlploggrpc/config.go#L38

When setting OTEL_EXPORTER_OTLP_INSECURE=true, this is ignored, as the `envInsecure` is using `envEndpoint`, when it should use something like:

```go
	envInsecure = []string{
		"OTEL_EXPORTER_OTLP_LOGS_INSECURE",
		"OTEL_EXPORTER_OTLP_INSECURE",
	}

```

**Comment by amanakin** [comment]
Hi there!
The current behavior makes sense, as stated in the [specification](https://opentelemetry.io/docs/specs/otel/protocol/exporter/):
> Insecure: Whether to enable client transport security for the exporter’s gRPC connection. This option only applies to OTLP/gRPC when an endpoint is provided without the http or https scheme - OTLP/HTTP always uses the scheme provided for the endpoint. Implementations MAY choose to not implement the insecure option if it is not required or supported by the underlying gRPC client implementation.

So when `OTEL_EXPORTER_OTLP_ENDPOINT` is passed, we use `Insecure=false` if the scheme is `https`, and `Insecure=true` otherwise.
https://github.com/open-telemetry/opentelemetry-go/blob/6d45f283c7abf2ee5284c769f9ae7109096d3564/exporters/otlp/otlplog/otlploggrpc/config.go#L400

I want to draw attention to the fact that the value of this environment variable must include a schema (or look like `//url.without.scheme:8080` for urls without scheme). This is because we use `url.Parse`, which states:
> Trying to parse a hostname and path without a scheme is invalid but may not necessarily return an error, due to parsing ambiguities.
(Probably that should be stated more explicitly)

Additionally, I'm not sure if it is correct behavior that if we create an exporter with these settings:
`otlploggrpc.New(nil, otlploggrpc.WithEndpointURL("https://some.url:8080"), otlploggrpc.WithInsecure())`
We will get an insecure connection with an https endpoint, because `WithInsecure` goes after `WithEndpointURL`.

**Comment by jpkrohling** [comment]
`OTEL_EXPORTER_OTLP_ENDPOINT` is not provided in my case, I'm relying on the default value.

**Comment by amanakin** [comment]
Yeah, you are right :) 
I just wanted to point out that the fix could be a bit tricky and not just a simple change to `envInsecure`.
Anyway, I can work on it.
