### ISSUE TITLE
Memory leak in global MeterProvider

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-go#5753]
### Description

Forked from https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5190

> I am able to reproduce the issue with these benchmarks:
> 
> ```go
> package bench
> 
> import (
> 	"testing"
> 
> 	"go.opentelemetry.io/otel"
> )
> 
> const (
> 	meterName   = "foo"
> 	metricName  = "bar"
> )
> 
> func BenchmarkSimple(b *testing.B) {
> 	b.ReportAllocs()
> 	meter := otel.Meter(meterName)
> 	for i := 0; i < b.N; i++ {
> 		meter.Int64Counter(metricName)
> 	}
> }
> ```
> 
> It has 1 allocation. Since we are repeatedly creating the same instrument, it should have 0 allocations. If I replace `otel.Meter` with a noop meterprovider or the real meter provider, it has 0 allocations. I believe the root cause is that we always append the instrument to the list of instruments for the global meter provider: e.g. https://github.com/open-telemetry/opentelemetry-go/blob/d776f74f7cd9cdaf5e4bb97aeb6b7e2d102e7d68/internal/global/meter.go#L142
> 
> We should instead maintain a map of instruments, and ensure that we only keep unique instruments, similar to what we did for the SDK.

### Expected behavior

We should not leak memory when a user creates the same instrument repeatedly

**Comment by Jesse-Bonfire** [comment]
It appears that this change has broken metrics that are registered before `otel.SetMeterProvider` is called. We are getting into a spot where the delegate on the `siUpDownCounter` isn't getting set as it looks like with the new map we are creating new ones and throwing away the old. But the old counter has been registered with `meter.RegisterCallback`
`
	i := &siUpDownCounter{name: name, opts: options}
	cfg := metric.NewInt64UpDownCounterConfig(options...)
	id := instID{
		name:        name,
		kind:        reflect.TypeOf(i),
		description: cfg.Description(),
		unit:        cfg.Unit(),
	}
	m.instruments[id] = i
	return i, nil`

I am pretty new to Otel and Go but this change seems to break the connection pools convention outlined here. 
https://github.com/open-telemetry/semantic-conventions/blob/422eeb71f40c73d1b195723cc1cffeb09abf2391/docs/database/database-metrics.md#connection-pools

Currently I am seeing this when instrumenting a Redis Cluster as it creates meters a connection pool for each node in the cluster. https://github.com/redis/go-redis/blob/233f97accde15bcb2e3d86ee744109b4dce34171/extra/redisotel/metrics.go#L85

This problem is removed if we apply the instrumentation after we call `otel.SetMeterProvider` because the delegate just creates the counter.

**Comment by Jesse-Bonfire** [comment]
I am able to reproduce the exception with the following test case

```
package bench

import (
	"context"
	"testing"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/metric"
	sdkmetric "go.opentelemetry.io/otel/sdk/metric"
)

const (
	meterName  = "foo"
	metricName = "bar"
)

func BenchmarkSimple(b *testing.B) {
	b.ReportAllocs()
	meter := otel.Meter(meterName)
	for i := 0; i < 5; i++ {
		m, _ := meter.Int64ObservableUpDownCounter(metricName)
		meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
			o.ObserveInt64(m, int64(10))
			return nil
		}, m)
	}
	p1 := sdkmetric.NewMeterProvider()
	otel.SetMeterProvider(p1)
}

```

**Comment by dashpole** [comment]
@Jesse-Bonfire I opened a new issue to track it: https://github.com/open-telemetry/opentelemetry-go/issues/5827
