### ISSUE TITLE
Prometheus exporter is incomplete

### ISSUE THREAD

**Issue by moorara** [open-telemetry/opentelemetry-go#652]
It seems the metric exporter for Prometheus is not yet complete. Specifically, I noticed the following features are missing:

   - [ ] Histogram metrics
   - [ ] Metric names are not namespace with the name passed to `Meter`
   - [ ] Labels are not reported

Is there any ongoing work to address these issues? If not, I can start working on them.

**Comment by jmacd** [comment]
Hi @moorara,
Sorry about the confusion. To these three points:
(1) Histogram is used for `Measure` instruments by default. What version did you test with?
(2) OTel has decided that `Meter` names are not to be treated as namespaces, those names are meant to identify the instrumenting library. This allows us to swap libraries that report the same metric. See https://github.com/open-telemetry/opentelemetry-specification/pull/552
(3) I'm pretty sure labels are reported, how did you test this? There's an open issue about Resources at the moment, which would map into "Const Labels" in prometheus, but that was just opened because resource support was added only recently.

I suspect the biggest source of confusion here is that the Prometheus exporter is not very configurable. For example, how do you set histogram boundaries? This is going to be the subject of the "Views API". See https://github.com/open-telemetry/oteps/pull/89.

I'm going to close this since I believe each of the points you raised is actually addressed. Thanks.

**Comment by moorara** [comment]
Hi @jmacd,

Thanks for explaining. I can confirm with the latest release of opentelemetry-go, these issues are addressed, however there's a bigger issue IMO. I opened the following issue for tracking it.
https://github.com/open-telemetry/opentelemetry-go/issues/689
