### ISSUE TITLE
Replacing http.read_bytes with net.read_bytes

### ISSUE THREAD

**Issue by vmihailenco** [open-telemetry/opentelemetry-go#676]
Currently othttp plugin uses `http.read_bytes` to report number of read bytes. I want to add something similar to DB spans - `db.read_bytes`. Would it make sense to replace `http.read_bytes` & `db.read_bytes` with `net.read_bytes` and add it to semantic conventions? Using one name would allow back-ends to automatically provide some aggregations & charts.

**Comment by MrAlias** [comment]
This issue is better suited for [the specification](https://github.com/open-telemetry/opentelemetry-specification) if it is about changing or settling on semantic conventions. If that is the case, @vmihailenco, can you close this issue and create one in that repo? 

My two cents are that it is ideal to understand the scope the bytes are being read from and the more general term of `net` is less useful in this sense.

**Comment by vmihailenco** [comment]
I understand that this eventually should be in the specification - just wanted to check if there is any interest.
