### ISSUE TITLE
API: In-process context propagation

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry-go#7]

**Comment by jmacd** [comment]
See this related draft:
https://github.com/open-telemetry/opentelemetry-specification/pull/75/files

**Comment by freeformz** [comment]
Why should it not be through context.Context (or an OpenCensus specific implementation of that interface)?

**Comment by jmacd** [comment]
It will use context.Context, and I don't think there's any reason to use a OTel-specific implementation of the interface. The prototype uses context.Context extensively, but there may still be things T.B.D. about how tags interoperate with instrumentation. This issue was a placeholder, I don't think anyone's against context.Context.

**Comment by jmacd** [comment]
We've reached the initial milestone, will open new issues for future related API concerns.
