### ISSUE TITLE
SDK: Add grpc plugin

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/opentelemetry-go#72]
Create grpc plugin for opentelemetry, similar to [ocgrpc](https://github.com/census-instrumentation/opencensus-go/tree/master/plugin/ocgrpc) for opencensus

**Comment by iredelmeier** [comment]
There are (at least) three routes we can go with this:

1. Use [`stats.Handler`](https://godoc.org/google.golang.org/grpc/stats#Handler). This is what [ocgrpc](https://github.com/census-instrumentation/opencensus-go/tree/master/plugin/ocgrpc) does.
1. Use interceptors ([`UnaryClientInterceptor`](https://godoc.org/google.golang.org/grpc#UnaryClientInterceptor), [`StreamClientInterceptor`](https://godoc.org/google.golang.org/grpc#StreamClientInterceptor), [`UnaryServerInterceptor`](https://godoc.org/google.golang.org/grpc#UnaryServerInterceptor), and [`StreamServerInterceptor`](https://godoc.org/google.golang.org/grpc#StreamServerInterceptor)). This is what both [opentracing go-grpc](https://github.com/opentracing-contrib/go-grpc) and [otgrpc](https://github.com/grpc-ecosystem/grpc-opentracing/tree/master/go/otgrpc) do.
1. Use some combination of both

`stats.Handler` exposes details such as the uncompressed and wire length of the payload, which aren't accessible through the interceptors.

On the other hand, the stream interceptors enable us to observe individual messages within the stream, rather than treating the whole stream as a single payload. `stats.Handler` doesn't facilitate this granularity. (Note that neither opentracing package currently does anything per-message, although it would probably be quite useful for many streaming use cases.)

Thoughts?

**Comment by rghetia** [comment]
Is it possible to associate different traces for each payload in case of stream interceptors? Otherwise long lived stream could end up having one parent creating 100s or 1000s of child span.

Can we support both with an option flag?

**Comment by iredelmeier** [comment]
Decision on the above, based on today's SIG, is to with **interceptors** at least for now. Longer term, we may do a combination of both.

**Comment by iredelmeier** [comment]
Closing this for now as I believe it makes sense to start with the converted Datadog gRPC plugin, which we should be able to make public soon.

**Comment by inigohu** [comment]
Any updates about otgrpc plugin?

**Comment by glerchundi** [comment]
Why was this issue closed? I think the decision to go through interceptors is a implementation detail but the feature request to create an interceptor/plugin still applies, right?

**Comment by rghetia** [comment]
reopening this as requested above.

**Comment by reicheltp** [comment]
I am currently implementing those interceptors for our company. I'll send a PR as soon as they're ready.

**Comment by sudeep-ib** [comment]
The attached PR #621, addresses tracing but does not implement stats. Is there a roadmap to including the stats plugin in opentelemetry. Is there an Issue that tracks it, or we could re-open this one?
@rghetia @jmacd

**Comment by rghetia** [comment]
@sudeep-ib please open a new issue for stats.
