### ISSUE TITLE
Add BatchObserver.Start() method

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#768]
There is a potential race condition between an observe callback being called and new instruments being registered to it. One solution is to use a lock between the callback and the code that registers instruments, but that leaves a lot to the user. 

Another option would be to return BatchObservers in an un-started state. Instruments can be added before calling Start() but not after. This will make it easier for the user.

**Comment by jmacd** [comment]
This is an example of the lock technique: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/44/commits/448936c885b93f5cac4af548628ca015378532b4

**Comment by stefanprisca** [comment]
I was looking a bit into this, and maybe I'm misunderstanding the issue, but there seems to be already an [Accumulator.asyncLock](https://github.com/open-telemetry/opentelemetry-go/blob/master/sdk/metric/sdk.go#L51) in place preventing this:

- [Accumulator.NewAsyncInstrument](https://github.com/open-telemetry/opentelemetry-go/blob/master/sdk/metric/sdk.go#L340) blocks the `asyncLock` while registering a new instrument
- [Accumulator.observeAsyncInstruments](https://github.com/open-telemetry/opentelemetry-go/blob/0e2fdfc682214f6656e700214d6885a348ad9862/sdk/metric/sdk.go#L420) also blocks the same `asyncLock` while collecting observations. 

Seeing that the observer callback is called after the lock in `Accumulator.observeAsyncInstruments` and that the actual registration of new instruments happens after the lock in `Accumulator.NewAsyncInstrument`, it seems like there shouldn't be an issue. But I might be missing something.

**Comment by jmacd** [comment]
The race I am concerned about will happen if the batch observer callback is invoked between calls to NewAsyncInstrument. If the callback executes before all the instruments are created, some of them will be nil. It's a good thing that lock is there, but there could still be a race between reading the value in the observer callback and writing the value returned by the constructor, since the lock has been released before the assignment.

If calling Observe on a nil instrument works without error (It probably does already, but it may not be tested), then this is less harmful than I worried. It could lead to confusing monitoring, I suppose, but the user also can arrange to setup these instruments before starting the SDK, which eliminates the problem. Would you agree that this is not an issue (assuming no crash)?

**Comment by stefanprisca** [comment]
I see the issue now. There is a [test](https://github.com/open-telemetry/opentelemetry-go/blob/master/sdk/metric/correct_test.go#L538) for uninitialized instruments  already.

In my opinion, there should be a `BatchObserver.Start` method to be explicit about its behavior. Otherwise it can be a bit confusing and lead to unexpected use-cases. And I would go a bit further to say that the whole process of creating async instruments and using them in the callback is a bit strange. The batch is required to initialize them which in turn requires the instruments to be initialized. It's kind of a chicken and the egg problem.

I made a small [demo](https://github.com/stefanprisca/opentelemetry-go/commit/6050efd130169d282a2d3810958fd4e7db282ba3?diff=unified) with an alternative, building on the same idea of having a `.Start` method. 
Basically, you have an `UnstartedBatchObserver` which can be used to register **uninitialized** instruments, and returns a pointer to them to be used later in the callback. The `UnstartedBatchObserver` then keeps track of these instruments as `unstartedInstruments`, and when starting it (by calling `AsStarted`), it will create the actual  `BatchObserver` and register all the instruments into it, replacing the previous pointers with the actual values.

Here's how it would look from a client perspective:
```golang
        ub := meter.NewUnstartedBatchObserver()
	ub, floatValueObs := ub.NewUnstartedFloat64ValueObserver("float.valueobserver.lastvalue")
	ub.AsStarted(func(_ context.Context, result metric.BatchObserverResult) {
			result.Observe(
				[]kv.KeyValue{
					kv.String("A", "B"),
				},
				floatValueObs.Observation(1),
			)
		})
```

**Comment by MrAlias** [comment]
This issues relates to the current metric SDK. The [metric SDK redesign project](https://github.com/orgs/open-telemetry/projects/22) includes changes to the SDK design that will make this issue obsolete. I'm closing so not wasted work is performed to address this.
