### ISSUE TITLE
Invalid HTTP status code 0

### ISSUE THREAD

**Issue by vmihailenco** [open-telemetry/opentelemetry-go#897]
http.Handler that does not explicitly sets HTTP status code gets following attributes:

```
status.code - Unknown
status.message - Invalid HTTP status code 0
```

At least the status message looks wrong because Go uses  `200 OK` status code when status code is not explicitly set. So the status code is known and is valid.

**Comment by Aneurysm9** [comment]
Can you provide a minimal repro?  I've tried to reproduce with the `othttp.Handler` and have been unable.  Its [`responseWriterWrapper`](https://github.com/open-telemetry/opentelemetry-go/blob/master/instrumentation/othttp/wrap.go#L94) ensures that the status is set.

I think that [the helper](https://github.com/open-telemetry/opentelemetry-go/blob/master/api/standard/http.go#L267) in `api/standard` is correct as 0 is not a valid HTTP status code.  Instrumentations should ensure that it is invoked with a valid status code.

**Comment by vmihailenco** [comment]
https://gist.github.com/vmihailenco/1028b37642cd04ed0222cfe8a3125dbf prints

```
"StatusCode":2,"StatusMessage":"Invalid HTTP status code 0"
```

>Its responseWriterWrapper ensures that the status is set.

It just records the status code. I don't see how it does anything beyond that.

**Comment by Aneurysm9** [comment]
> It just records the status code. I don't see how it does anything beyond that.

The `responseWriterWrapper` will ensure that the status code is `http.StatusOK` if `Write()` is called before `WriteHeader()`, in conformance with the [`http.ResponseWriter`](https://golang.org/pkg/net/http/#ResponseWriter) interface.  Your repro does neither.  In that case the `rww.statusCode` value remains at its zero value since nothing has updated it.  

Is there a valid use for an `http.Handler` that does not call either `Write()` or `WriteHeader()` on its provided `http.ResponseWriter`?

**Comment by vmihailenco** [comment]
>Is there a valid use for an http.Handler that does not call either Write() or WriteHeader() on its provided http.ResponseWriter?

No calls to WriteHeader means `WriteHeader(200)`. What is wrong with that?

**Comment by vmihailenco** [comment]
>No calls to either WriteHeader() or Write() is undefined behavior.

In my universe it always sends 200 OK.
